//  Copyright (C) 2024, Max Piochowiak and Reiner Dolp, Karlsruhe Institute of Technology
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.

#version 460
#extension GL_GOOGLE_include_directive : enable

layout (local_size_x = 8, local_size_y = 8) in;

layout (set = 0, binding = 1, rgba8) uniform restrict writeonly image2D IMAGE_out;

layout (std140, row_major, set = 0, binding = 2) uniform options {
    uint g_frameIdx;
};

#include "util.glsl"


void main() {

    ivec2 tableSize = imageSize(IMAGE_out);
    ivec2 threadId = ivec2(gl_GlobalInvocationID.xy);

    if (isHelperLane(threadId, tableSize)) {
        return;
    }

    imageStore(IMAGE_out, threadId, vec4(sin(float(g_frameIdx)*0.001)*0.5+0.5, 0.0, 0.0, 1.0));
}
