#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_buffer_reference_uvec2 : require
#extension GL_KHR_shader_subgroup_basic : require

#ifndef SUBGROUP_SIZE
    #define SUBGROUP_SIZE 64
#endif

// TODO: instead of invoking brick_idx_count * SUBGROUP_SIZE for .x, invoke .x=SUBGROUP_SIZE, .y=brick_idx_count?
// brick_idx_count * SUBGROUP_SIZE invocations: one subgroup is responsible for decompressing one brick
layout (local_size_x = SUBGROUP_SIZE, local_size_y = 1, local_size_z = 1) in;


#include "csgv_bindings.glsl"

#include "util.glsl"
#include "volcanite/compression/csgv_utils.glsl"
#define CSGV_DECODING_ARRAY g_cache

#define CSGV_SHARED_MEMORY_BRICK_ENCODING s_brick_encoding
#define MAX_BRICK_ENCODING_32BIT_LENGTH 12288
shared uint[MAX_BRICK_ENCODING_32BIT_LENGTH] s_brick_encoding;

#include "volcanite/compression/encoder_serial.glsl"
#include "volcanite/compression/compressed_segmentation_volume_parallel.glsl"

void main() {
    assert(gl_NumSubgroups == 1, "decompression assumes exactly one subgroup per workgroup");
    assert(gl_SubgroupSize == SUBGROUP_SIZE && gl_WorkGroupSize.x == SUBGROUP_SIZE && gl_WorkGroupSize.y == 1u
            && gl_WorkGroupSize.z == 1u, "decompression assumes workgroup size equal to the subgroup size");

    // one workgroup decompresses one brick
    const uint workgroup_thread_id = gl_LocalInvocationID.x;
    const uint workgroup_size = gl_WorkGroupSize.x;

    const uint brick_idx = gl_WorkGroupID.x;
    if (isHelperLane(brick_idx, g_brick_count.x * g_brick_count.y * g_brick_count.z))
        return;
    const uvec3 brick = brick_idx2pos(brick_idx, g_brick_count);
    const uint brick_info_pos = brick_idx * 4u;

    // if this brick has a valid request slot, it requests decompression. Otherwise, it can be ignored.
    if (g_brick_info[brick_info_pos + BRICK_INFO_REQ_SLOT] == INVALID) {
        return;
    }

    // obtain requested inv_lod and previously assigned cache_idx
    const uint target_inv_lod = g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD];
    assert(0 < target_inv_lod && target_inv_lod < g_lod_count, "brick has slot index but requests zero or invalid lod");
    const uint cache_idx = g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX];

    barrier();

    // reset the requested LOD. the renderer will have to flag everything visible again
    if (workgroup_thread_id == 0u) {
        g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] = max(g_lod_count, g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD]);
    }

    // decompression requested for brick, but brick could not receive a free cache region
    if (cache_idx == INVALID) {
        if (workgroup_thread_id == 0u) {
            g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD] = INVALID;
            g_brick_info[brick_info_pos + BRICK_INFO_REQ_SLOT] = INVALID;
        }
        return;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //                  perform the decompression of the brick into the previously assigned cache region              //
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    #ifdef SEPARATE_DETAIL
        assert(false, "Parallel decompression does not support detail separation yet");
        // assert(!(target_inv_lod == g_lod_count - 1U
        //        && (g_detail_buffer_dirty == 1u || g_detail_starts[brick_idx] == g_detail_starts[brick_idx+1])),
        //        "detail buffers marked dirty but the provision shader requested detail decoding");
    #endif
    // 1. copy brick encoding to shared memory
    // TODO: care about detail encoding! should be glued to the back of the same region
    EncodingRef global_brick_encoding = getBrickEncodingRef(brick_idx);
    const uint brick_encoding_length = getBrickEncodingLength(brick_idx);
    assert(brick_encoding_length < MAX_BRICK_ENCODING_32BIT_LENGTH, "shared memory brick encoding buffer is too small");
    // TODO: copying one uvec4 with each thread is still coalescing and much faster!
    for (uint e = workgroup_thread_id; e < brick_encoding_length; e += workgroup_size) {
        s_brick_encoding[e] = global_brick_encoding.buf[e];
    }

    // some validation of the brick encoding:
    if (!verifyBrickCompressionShared(0, brick_encoding_length))
        return;


    memoryBarrierShared();
    barrier();

    // 2. iterate over output voxels of brick (cache positions) for the requested LOD and decompress each one in parallel
    const uint decoded_brick_start_uint = cache_idx * g_cache_base_element_uints;
    const uint output_voxel_count = 1u << (3u * target_inv_lod);
    const uint target_brick_size = 1u << target_inv_lod;
    // The workgroup_size many work items iterate through the Morton indexing order from front to back.
    // The threads work on the next following items in parallel.
    //
    // If workgroup_size >= number_of_output_voxels: each thread computes ONE output element
    // If workgroup_size <  number_of_output_voxels: each thread computes multiple output elements
    // With a workgroup_size equal to the subgroup size, optimization like vulkan subgroup operations are posssible.
    uint output_i = workgroup_thread_id;
    while (output_i < output_voxel_count) {
        decompressCSGVVoxelSharedMemory(output_i, brick_encoding_length, uvec3(g_brick_size),
                                        target_inv_lod, decoded_brick_start_uint);
        // barrier()
        output_i += workgroup_size;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    // the brick was successfuly decompressed into the cache into the requested inverse LOD, the request can be removed.
    if (workgroup_thread_id == 0u) {
        g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD] = target_inv_lod;
        g_brick_info[brick_info_pos + BRICK_INFO_REQ_SLOT] = INVALID;
    }
}
