//  Copyright (C) 2024, Fabian Schiekel and Max Piochowiak, Karlsruhe Institute of Technology
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.

#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_buffer_reference_uvec2 : require

layout (local_size_x = 8, local_size_y = 8) in;

#include "util.glsl"
#include "volcanite/renderer/csgv_bindings.glsl"
#include "volcanite/renderer/framebuffer.glsl"
#include "volcanite/renderer/csgv_materials.glsl"
#include "volcanite/renderer/dummy_envmap.glsl"

#include "debug_colormaps.glsl"

vec3 rgb2srgb(vec3 x) {
    // simple mapping:
    //return pow(x, 1.f / vec3(2.4f));

    #pragma unroll
    for (int i = 0; i < 3; i++) {
        if (x[i] < 0.0031308f)
            x[i] *= 12.92f;
        else
            x[i] = 1.055f * pow(x[i], 1.0f/2.4f) - 0.055f;
    }
    return x;
}

float luminance(vec3 v) {
    return 0.2126 * v.x + 0.7152 * v.y + 0.0722 * v.z;
}

vec3 tonemap_ACES(vec3 x)
{
    float a = 2.51f;
    float b = 0.03f;
    float c = 2.43f;
    float d = 0.59f;
    float e = 0.14f;
    return clamp((x*(a*x+b))/(x*(c*x+d)+e), vec3(0.f), vec3(1.f));
}

float gaussian(float x, float sigma) {
    return exp(-0.5 * (x * x) / (sigma * sigma));
}

// CODE PARTIALLY ADAPTED FROM
// https://github.com/NVIDIAGameWorks/Falcor/blob/master/Source/RenderPasses/SVGFPass/SVGFAtrous.ps.slang
/***************************************************************************
 # Copyright (c) 2015-23, NVIDIA CORPORATION. All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions
 # are met:
 #  * Redistributions of source code must retain the above copyright
 #    notice, this list of conditions and the following disclaimer.
 #  * Redistributions in binary form must reproduce the above copyright
 #    notice, this list of conditions and the following disclaimer in the
 #    documentation and/or other materials provided with the distribution.
 #  * Neither the name of NVIDIA CORPORATION nor the names of its
 #    contributors may be used to endorse or promote products derived
 #    from this software without specific prior written permission.
 #
 # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS "AS IS" AND ANY
 # EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 # IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 # PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 # CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 # EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 # PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 # PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 # OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **************************************************************************/

float computeWeight(float depthCenter, float depthP, float phiDepth, float luminanceIllumCenter,
                    float luminanceIllumP, float phiIllum) {

    float weightZ = (phiDepth == 0) ? 0.f : 1.f;
    weightZ = (phiDepth == 0) ? 0.f : abs(depthCenter - depthP) / phiDepth;

    const float weightLillum = 0.f;
    //const float weightLillum = abs(luminanceIllumCenter - luminanceIllumP) / phiIllum;

    const float weightIllum = exp(-max(weightLillum, 0.0) - max(weightZ, 0.0));
    return weightIllum;
}

float computeVarianceCenter(ivec2 ipos, const ivec2 viewport_size) {
    // not yet supported
    return 1.f;
    float sum_m1 = 0.f;
    float sum_m2 = 0.f;
    float sumW = 0.f;
    const float kernel[2][2] = {
    { 1.0 / 4.0, 1.0 / 8.0 },
    { 1.0 / 8.0, 1.0 / 16.0 },
    };

    // collect first and second momentum and blur with gaussian kernel
    const int radius = 1; // 3x3 kernel
    for (int yy = -radius; yy <= radius; yy++) {
        for (int xx = -radius; xx <= radius; xx++) {
            const vec2 block_pixel = ipos + vec2(xx, yy);
            const float k = kernel[abs(xx)][abs(yy)];

            if (any(lessThan(block_pixel, ivec2(0))) || any(greaterThanEqual(block_pixel, viewport_size)))
                continue;

            float lum = luminance(imageLoad(denoisingBuffer[pc.denoising_iteration % 2], ivec2(block_pixel)).rgb);
            sum_m1 += lum * k;
            sum_m2 += (lum * lum) * k;
            sumW += k;
        }
    }
    sum_m1 /= max(sumW, 1e-8f);
    sum_m2 /= max(sumW, 1e-8f);
    return sum_m2 - (sum_m1 * sum_m1);
}

vec3 getAlbedoOfLabel(uint label) {
    // TODO: fix bugs with albedo demodulation
    //return vec3(1.f);

    // the G buffer stores the invalid label for rays that hit no surface
    if (label == INVALID)
        return vec3(1.f);

    const int material = getMaterial(label);
    if (material < 0) {
        assert(false, "G-buffer must not contain labels that are invisible");
        return vec3(1.f);
    } else {
        return getColor(label, material).rgb;
    }
}

// inplace alpha blending of pixel_rgba with the background color that is visible for the primary ray through block_pixel
vec4 blendWithBackground(ivec2 pixel, vec4 pixel_rgba) {
    // deterministic computation of the view ray
    vec2 subpixel_offset = randomVec3(pixel, g_camera_still_frames).xy;
    vec2 fragCoord = (vec2(pixel) + subpixel_offset) / vec2(imageSize(inpaintedOutColor));
    vec3 viewRayDirection = normalize((g_pixel_to_ray_direction_world_space * vec3(pixel + subpixel_offset, 1.0f)).xyz);
    // blend with background
    pixel_rgba = pixel_rgba.a * pixel_rgba + (1.f - pixel_rgba.a) * get_background_color(fragCoord, viewRayDirection);
    return pixel_rgba;
}

#include "volcanite/renderer/csgv_debug_resolve.glsl"

void writeFinalFramebuffer(ivec2 pixel, vec4 accum_rgba) {
#if 0
    // debug input buffer (left) vs. upsampled and denoised (right) output
    if (pixel.x < viewport_size.x / 2) {
        uint sample_count_block = max(imageLoad(accuSampleCountOut, pixel).r, 1u);
        accum_rgba = imageLoad(accumulationOut, pixel) / float(sample_count_block);
    }
#endif

    // perform tonemapping and color space conversion
    if(g_tonemap_enable) {
        accum_rgba.rgb = tonemap_ACES(accum_rgba.rgb);
    }
    // accum_rgba.rgb = rgb2srgb(accum_rgba.rgb);

    DEBUG_img_g_buffer(pixel, accum_rgba, false);

    // blend with background and output to display image
    imageStore(inpaintedOutColor, pixel, blendWithBackground(pixel, accum_rgba));
}

void main() {
    // obtain pixel and fragment coordinates
    const ivec2 viewport_size = imageSize(inpaintedOutColor);
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

    // only one thread per pixel block
    if (isHelperLane(pixel, viewport_size))
        return;

    // upsampling / denoising may be disabled or faded out
    const float fade = g_denoise_fade_enable ? min(1.f, g_denoise_fade_sigma / sqrt(g_camera_still_frames / (g_subsampling * g_subsampling))) : 1.f;
    if (!g_svgf_enable || fade < 0.01f) {
        if (pc.denoising_iteration == pc.last_denoising_iteration) {
            writeFinalFramebuffer(pixel, imageLoad(denoisingBuffer[0], pixel));
        }
        return;
    }

    // read RGB radiance + alpha that was accumulated for this pixel so far.
    // it was already normalized with the sample count
    // an alpha value < 0 indicates that this pixel did not receive a single sample yet
    vec4 pixel_rgba = imageLoad(denoisingBuffer[pc.denoising_iteration % 2], pixel);
//    if (pc.denoising_iteration == 0) {
//        uint sample_count = max(imageLoad(accuSampleCountOut, pixel).r, 1u);
//        pixel_color /= float(sample_count);
//    }

    // unpack the G-Buffer for the current output pixel (center)
    // center_sampled is false if the pixel did not receive a sample yet -> requires upsampling!
    float center_normalized_depth;
    vec3 center_normal;
    uint center_label;
    const bool center_sampled = unpackGBufferRGB16(imageLoad(gBuffer, pixel).rgb,
                                                   center_label, center_normal, center_normalized_depth);
    if (pc.denoising_iteration == 0u) {
        if (!center_sampled) {
            // marking non-sampled pixels for the first iteration must happen here. Otherwise, the renderer shader
            // would have to read from gBuffer to check if the pixel received a sample in an earlier frame.
            pixel_rgba.a = -1.f;
        } else {
            // demodulade rgb by albedo
            pixel_rgba.rgb /= getAlbedoOfLabel(center_label);
        }
    }

    float pixel_luminance = luminance(pixel_rgba.rgb);


    // MULTI-PASS À-TROUS FILTER -----------------------------------------------------------------------------------
    // could become SVGF
    // for now only À-Trous filter w/o any variance estimation or temporal accumulation
    const int step_size = 1 << pc.denoising_iteration;
    // use a Gaussian instead of B-spline kernel (see Dolp et al. "A Fast GPU Schedule For À-Trous Wavelet-Based Denoisers")
    // we do not overlbur in the first iteration, as we found artifacts to be reduced with the constant Gauss kernel
    // weights defined for 3x3 kernel [0.5, 1, 0.5] in 1D, outer product as [1 2 1]
    //                                                                      [2 4 2]
    //                                                                      [1 2 1]
    const vec4 kernel_weights = vec4(1.f, 0.5f * fade, 0.25f * fade * fade, 0.125f * fade * fade);

    const float var = 1.f; //computeVarianceCenter(pixel, viewport_size);

//    // for upsampling: halluciante a g buffer sample from the (3,3)*step_size neighborhood
//    {
//        // if two neighbors along one of the four axes have the same G-buffer, use it as the center pixel's G-buffer
//        ivec2 axis_delta[4] = ivec2[](ivec2(1, 0), ivec2(0, 1), ivec2(1, 1), ivec2(-1, 1));
//        // axis 0   axis 1    axis 2   axis 3
//        //  - - -    - 0 -    0 - -    - - 1
//        //  0 - 1    - - -    - - -    - - -
//        //  - - -    - 1 -    - - 1    0 - -
//
//        // TODO implement G buffer hallucination in resolve pass
//    }

    const float EPS = 0.01f;
    const float phi_Lillumination = g_illumination_sigma * sqrt(var) + EPS;
    //const float phi_Lillumination = 1.f; // unnused for now
    const float phi_depth = max(center_normalized_depth / 2.f, 1e-8) * step_size;

    vec4 accum_rgba = vec4(0.f);
    float weight = 1.f;
    float weight_sum  = 0.f;

    for (int dy = -g_denoise_filter_kernel_size; dy <= g_denoise_filter_kernel_size; dy++) {
        for (int dx = -g_denoise_filter_kernel_size; dx <= g_denoise_filter_kernel_size; dx++) {
            ivec2 filter_pixel = pixel - (ivec2(dx, dy) * step_size);

            // do not sample outside image plane, cast to uvec to catch values < 0
            if (isHelperLane(uvec2(filter_pixel), uvec2(viewport_size)))
                continue;

            // if upsampling is required and the pixel already received a color:
            // do not blur in later passes to prevent overblur!
            // also: do not blur if denoising is disabled
            if (!center_sampled || !g_bilateral_enable) {
                if (pixel_rgba.a >= 0.f) {
                    accum_rgba = pixel_rgba;
                    weight_sum = 1.f;
                    break;
                }
            }

            // unpack filter pixel
            float normalized_depth;
            vec3 normal;
            uint label;
            bool sampled = unpackGBufferRGB16(imageLoad(gBuffer, filter_pixel).rgb, label, normal, normalized_depth);

            // filter pixels that did not receive a sample yet are skipped:
            // - in the first iteration, these are marked by the !sampled return value of the G-Buffer query
            // - in later queries, these are marked with an rgba alpha value < 0
            if (pc.denoising_iteration == 0 && !sampled)
                continue;

            vec4 rgba = imageLoad(denoisingBuffer[pc.denoising_iteration % 2], filter_pixel);

            // filter pixels that did not receive a single sample yet are marked with negative values and skipped
            if (pc.denoising_iteration > 0 && rgba.a < 0.f) {
                continue;
            }

            // if the center pixel received a sample (valid G-Buffer): denoising - compute filter weights from G-Buffer
            // otherwise: upsampling - fill with blurred neighbor colors
            if (center_sampled) {
                // quantized normals: either (+/-) 90 or (+/-) 180 degree angle
                // => max(cos, 0) = weightN is either 0 or 1
//                if (label != center_label)
//                    continue;
                if (any(notEqual(center_normal, normal)))
                    continue;

                // in the first iteration: demodulate filter pixel radiance by filter pixel albedo
                // only if not upsampling! there is no way to re-modulate if the center is not sampled.
                if (pc.denoising_iteration == 0u)
                    rgba.rgb /= getAlbedoOfLabel(label);
            }

            const float kernel = kernel_weights[abs(dx)] * kernel_weights[abs(dy)];
            const float w = (phi_depth == 0.f || !center_sampled) ? 1.f : exp(-abs(normalized_depth - center_normalized_depth) / phi_depth); //computeWeight(center_normalized_depth, normalized_depth, phi_depth, pixel_luminance, luminance(rgba.rgb), phi_Lillumination);
            weight = w * kernel;

            accum_rgba += rgba * weight;
            weight_sum += weight;
        }
    }

//    if (isCenterWorkItem()) {
//        debugPrintfEXT("this is iteration %u of %u, reading from buffer %u writing to %u", pc.denoising_iteration, pc.last_denoising_iteration, (pc.denoising_iteration % 2u), 1u - (pc.denoising_iteration % 2u));
//    }

    if (weight_sum > 0.f)
        accum_rgba /= weight_sum;

//    if (pc.denoising_iteration > 0)
//        accum_rgba = imageLoad(denoisingBuffer[pc.denoising_iteration % 2], pixel);

    if (pc.denoising_iteration < pc.last_denoising_iteration) {
        //  before last iteration:      À-trous feedback to next denoising iteration kernel in HDR
        // mark pixels from a filter step that did not receive a single rendered sample with a negative alpha value
        if (weight_sum <= 0.f)
            accum_rgba.a = -1.f;

        // store color for next iteration
        imageStore(denoisingBuffer[1u - (pc.denoising_iteration % 2u)], pixel, accum_rgba);
    } else {
        // last iteration:              final pixel output in LDR
        // re-modulate with albedo
        if (center_sampled) {
            accum_rgba.rgb *= getAlbedoOfLabel(center_label);
        }
        writeFinalFramebuffer(pixel, accum_rgba);
    }
}
