#version 460
#extension GL_GOOGLE_include_directive : enable

layout (local_size_x = 8, local_size_y = 8) in;

layout (set = 0, binding = 0, rgba8) uniform restrict writeonly image2D IMAGE_out;
layout (set = 0, binding = 1) uniform sampler1D SAMPLER_TF1D;
layout (set = 0, binding = 2) uniform sampler2D SAMPLER_TF2D;
layout (set = 0, binding = 3) uniform options {
    int mode;
};
const int MODE_TF1D = 0;
const int MODE_TF2D = 1;

#include "util.glsl"

void main() {

    ivec2 viewport_size = imageSize(IMAGE_out);
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

    if (isHelperLane(pixel, viewport_size)) {
        return;
    }

    vec2 fragCoord = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5)) / vec2(viewport_size);

    if (mode == MODE_TF1D) {
        if (fragCoord.y > 0.25 && fragCoord.y < 0.75) {
            imageStore(IMAGE_out, pixel, texture(SAMPLER_TF1D, fragCoord.x));
        } else if (fragCoord.y > 0.1 && fragCoord.y < 0.2) {
            vec4 col = texture(SAMPLER_TF1D, fragCoord.x);
            imageStore(IMAGE_out, pixel, vec4(col.a, col.a, col.a, 1));
        } else {
            imageStore(IMAGE_out, pixel, vec4(0, 0, 0, 0));
        }
    } else if (mode == MODE_TF2D) {
        fragCoord.y = 1 - fragCoord.y;
        imageStore(IMAGE_out, pixel, texture(SAMPLER_TF2D, fragCoord));
    }
}
