#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable

layout (local_size_x = 16) in;


#include "csgv_bindings.glsl"

// includes
#include "cpp_glsl_include/csgv_constants.h"
#include "util.glsl"
#include "volcanite/compression/csgv_utils.glsl"

void main() {
    // at the beginning of this shader:
    // cache element ownership
    // - (BRICK_INFO_INDEX < INVALID) <=> (BRICK_INFO_CUR_INV_LOD < g_lod_count) <=> the brick still owns a cache element
    // - REQ_SLOT < INVALID <=> the brick needs a cache element <=> the REQ_SLOT is a valid entry for its REQ_LOD
    // - REQ_SLOT < INVALID => BRICK_INFO_INDEX == INVALID
    // - the ASSIGN_REQUESTED_BLOCKS for each LoD contains the number of requested blocks for this LoD.
    // - all SLOT indices < ASSIGN_REQUESTED_BLOCKS are uniquely assigned to one block each
    // visibility
    // - BRICK_INFO_REQ_INV_LOD < g_lod_count means the brick is visible in renderer AND had visible palette entries in the frame before
    // - BRICK_INFO_REQ_INV_LOD = g_lod_count means the brick contains visible labels in its palette
    // - (BRICK_INFO_REQ_INV_LOD > g_loc_count) means that the brick is guaranteed to be invisible
    // stacks
    // - if a brick is no longer visible but held an element in cache, it was freed and added to the free_block_stack

    // ToDo: we could do this in ONE thread only and do a for-loop over all LoDs. This could guarantee to allocate smaller/coarser LoDs even if finer LoDs would increase the cache_top too high
    // find out for which lod we compute everything
    // invocation 0 = LoD 1 which is the coarsest that we handle and uses 2x2x2 uints for storage in cache (= one base element)
    uint inv_lod = gl_GlobalInvocationID.x + 1u;
    if (isHelperLane(inv_lod, g_lod_count))
        return;

    // for g_debug_step_count
    {
        gpu_raymarch_samples = 0u;
        gpu_bbox_hits = 0u;
        gpu_blocks_in_cache[inv_lod - 1u] = 0u;
    }

    // compute how many new elements we need because more elements for this LoD are
    uint numberOfRequests = g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_REQUESTED_BLOCKS];
    if(numberOfRequests == 0u) {
        g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_START] = INVALID;
        g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_COUNT] = 0u;

#ifdef SEPARATE_DETAIL
        // keeping track of the cache usage for CPU download
        g_detail_requests[g_request_buffer_capacity + 1u] =  g_assign_info[(g_lod_count - 1u) * ASSIGN_ELEMS_PER_LOD];
#endif

        gpu_blocks_decoded[inv_lod - 1u] = 0u;
        return;
    }

    // number of elements that are available on the free stack for this LoD
    uint numberOfFreeBlocks = g_free_block_stacks[(g_lod_count - 1u) * g_free_stack_capacity + (inv_lod - 1u)];
#if 0
    if(numberOfFreeBlocks > 0u)
        debugPrintfEXT("we have %u free blocks in LoD %u (frame %u)", numberOfFreeBlocks, inv_lod, g_frame);
#endif
    // find out how many elements for this LoD can not be aquired from the free stack
    int numberOfNewBlocks = int(numberOfRequests) - int(numberOfFreeBlocks);

    // .. all of the reuqests fulfilled from the free stack
    if(numberOfNewBlocks < 0) {
        g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_START] = INVALID;
        g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_COUNT] = 0u;
        // reset the request slot counter for the next frame
        g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_REQUESTED_BLOCKS] = 0u;

        gpu_blocks_decoded[inv_lod - 1u] = numberOfRequests;
        return;
    }

    // .. we need to aquire new elements from the cache top
    const int elemSizeInCache = 1 << (3 * (int(inv_lod) - 1)); // number of 2x2x2 blocks we need for storing one element of this LoD in g_cache
    uint newBaseElemsToRequest = uint(numberOfNewBlocks * elemSizeInCache);

    const uint cache_top = (g_lod_count - 1u) * ASSIGN_ELEMS_PER_LOD;
    uint start_idx = atomicAdd(g_assign_info[cache_top], newBaseElemsToRequest);
    if(start_idx >= g_cache_capacity) {
        // we can't create ANY new elements. revert and store the info in our ASSIGN_ location
        atomicAdd(g_assign_info[cache_top], uint(-int(newBaseElemsToRequest)));
        g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_START] = INVALID;
        g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_COUNT] = 0u;
#ifndef NDEBUG
        debugPrintfEXT("for inv. LoD %u we couldn't aquired any of the %u new elements in addition to the %u free stack blocks for %u requests. Cache usage at %u / %u. (100%%)", inv_lod, newBaseElemsToRequest, numberOfFreeBlocks, numberOfRequests, (start_idx), g_cache_capacity);
#endif
        gpu_blocks_decoded[inv_lod - 1u] = numberOfFreeBlocks;
    }
    else if (start_idx + newBaseElemsToRequest >= g_cache_capacity) {
        // we can't create ALL new base elements. revert as necessary and allocate the rest.
        uint possible_number_of_blocks = (g_cache_capacity - start_idx) / elemSizeInCache;
        atomicAdd(g_assign_info[cache_top], uint(-(newBaseElemsToRequest - possible_number_of_blocks * elemSizeInCache)));
        g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_START] = start_idx;
        g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_COUNT] = possible_number_of_blocks; // can be zero!
#ifndef NDEBUG
        debugPrintfEXT("for inv. LoD %u we partially aquired %u / %u new elements in addition to the %u free stack blocks for %u requests. Cache usage at %u / %u. (%3.1f%%)", inv_lod, possible_number_of_blocks, newBaseElemsToRequest, numberOfFreeBlocks, numberOfRequests, (start_idx + possible_number_of_blocks * elemSizeInCache), g_cache_capacity, 100.f*float(start_idx + possible_number_of_blocks * elemSizeInCache)/float(g_cache_capacity));
#endif

        gpu_blocks_decoded[inv_lod - 1u] = possible_number_of_blocks + numberOfFreeBlocks;
    }
    else {
        // we could create everything and have now a consecutive space in g_cache for all the new elements
        // that can't be obtained from the freeBlockStack
        g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_START] = start_idx;
        g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_COUNT] = uint(numberOfNewBlocks);
#ifndef NDEBUG
        debugPrintfEXT("for inv. LoD %u we aquired all %u new elements in addition to the %u free stack blocks to fullfill %u requests. Cache usage at %u / %u. (%3.1f%%)", inv_lod, newBaseElemsToRequest, numberOfFreeBlocks, numberOfRequests, (start_idx + newBaseElemsToRequest), g_cache_capacity, 100.f*float((start_idx + newBaseElemsToRequest))/float(g_cache_capacity));
#endif
        gpu_blocks_decoded[inv_lod - 1u] = uint(numberOfNewBlocks) + numberOfFreeBlocks;
    }

    // reset the request slot counter for the next frame
    g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_REQUESTED_BLOCKS] = 0u;

#ifdef SEPARATE_DETAIL
    // we also store the current cache top index into a designated location within the request array
    // since the request array will be downloaded to the GPU. This allows the GPU to force a cache clear,
    // meaning the garbage collection step.
    g_detail_requests[g_request_buffer_capacity + 1u] =  g_assign_info[cache_top];
#endif
    gpu_cache_size = g_assign_info[cache_top];




    // after this shader execution:
    // assign info
    // - ASSIGN_NEW_BLOCK_START contains the first index (measured in 2x2x2 elements) in g_cache where the new elements for this LoD start
    // - ASSIGN_NEW_BLOCK_COUNT contains the number of elements (measured in LxLxL elements) in g_cache for this LoD available from there
    // - START and COUNT are guaranteed to remain within g_cache_capacity
    // stacks
    // - if a brick is no longer visible but held an element in cache, it was freed and added to the free_block_stack
    // - the lod_counter elements at the end of the free_block_stack are all reset to zero
    //
    // basically this shader trys to provide as much new space in g_cache as we need in addition to the freeBlockStack for all LoDs
}
