#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable

layout (local_size_x = 8, local_size_y = 8) in;

#include "csgv_bindings.glsl"
#include "util.glsl"

vec3 rgb2srgb(vec3 x) {
    return pow(x, vec3(2.2f));
}

vec3 tonemap_ACES(vec3 x)
{
    float a = 2.51f;
    float b = 0.03f;
    float c = 2.43f;
    float d = 0.59f;
    float e = 0.14f;
    return clamp((x*(a*x+b))/(x*(c*x+d)+e), vec3(0.f), vec3(1.f));
}

void main() {
    // obtain pixel and fragment coordinates
    const ivec2 viewport_size = imageSize(inpaintedOutColor);
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

    // we output a low resolution image were multiple pixel are merged into one if the image does not have all pixels set yet
    // not sure if this formula is right..
    const int current_block_size = clamp(2 << int(log2(g_subsampling / int(ceil(sqrt(g_camera_still_frames + 1))))), 1, g_subsampling);
    pixel *= current_block_size;

    // only one thread per pixel block
    if(isHelperLane(pixel, viewport_size))
        return;

    // rgb stores radiance sum, alpha stores number of samples
    vec4 accum_color;

    // after enough frames have passed, the block size is one <=> each pixel has a valid sample
    if(current_block_size == 1) {
        accum_color = imageLoad(feedbackOut, pixel);
    }
    // otherwise, we compute the average color of the whole block
    else {
        accum_color = vec4(0.f);
        // compute an average of all pixels in this
        ivec2 block_pixel;
        for(block_pixel.y = pixel.y; block_pixel.y < pixel.y + current_block_size; block_pixel.y++) {
            for(block_pixel.x = pixel.x; block_pixel.x < pixel.x + current_block_size; block_pixel.x++) {
                // if no sample is set for the pixel yet, we assume that the color is 0
                if(!isHelperLane(block_pixel, viewport_size))
                    accum_color += imageLoad(feedbackOut, block_pixel);
            }
        }
    }

    // weight by sample count
    if(accum_color.a > 0.f)
        accum_color.rgb /= accum_color.a;

    // perform tonemapping and color space conversion
    if(g_tonemap_enable > 0) {
        accum_color.rgb = tonemap_ACES(accum_color.rgb);
        accum_color.rgb = rgb2srgb(accum_color.rgb);
    }

    // output to display image
    if(current_block_size == 1) {
        imageStore(inpaintedOutColor, pixel, vec4(accum_color.rgb, 1.f));
    }
    // if the block size is > 1, write to all those pixels
    else {
        ivec2 block_pixel;
        for(block_pixel.y = pixel.y; block_pixel.y < pixel.y + current_block_size; block_pixel.y++) {
            for(block_pixel.x = pixel.x; block_pixel.x < pixel.x + current_block_size; block_pixel.x++) {
                if(!isHelperLane(block_pixel, viewport_size))
                imageStore(inpaintedOutColor, block_pixel, vec4(accum_color.rgb, 1.f));
            }
        }
    }
}
