#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_buffer_reference_uvec2 : require

layout (local_size_x = 4, local_size_y = 4, local_size_z = 4) in;


#include "csgv_bindings.glsl"

// includes
#include "cpp_glsl_include/csgv_constants.h"
#include "util.glsl"
#include "volcanite/compression/csgv_utils.glsl"

bool pushFreeBlockStack(uint inv_lod, uint value) {
    uint pos = atomicAdd(g_free_block_stacks[(g_lod_count - 1u) * g_free_stack_capacity + (inv_lod - 1u)], 1u);
    if(pos > g_free_stack_capacity) {
        // no free index for us
        assert(false, "couldn't push to free block stack because it is full");
        atomicAdd(g_free_block_stacks[(g_lod_count - 1u) * g_free_stack_capacity + (inv_lod - 1u)], uint(-1));
        return false;
    }
    else {
        g_free_block_stacks[(inv_lod - 1u) * g_free_stack_capacity + pos] = value;
        return true;
    }
}


void main() {
    // at the beginning of this shader:
    // cache element ownership
    // - (BRICK_INFO_INDEX < INVALID) <=> (BRICK_INFO_CUR_INV_LOD < g_lod_count) <=> the brick owns a cache element
    // - if BRICK_INFO_INDEX < INVALID, the brick owns a cache element in this position with size BRICK_INFO_CUR_INV_LOD
    // visibility
    // - BRICK_INFO_REQ_INV_LOD < g_lod_count means the brick is visible in renderer AND had visible palette entries in the frame before
    // stacks
    // - ASSIGN_REQUESTED_BLOCKS was reset to zero before the shader execution started
    // - the top pointers in the g_free_block_stacks point to the next free location in the LoD stack

    // find out for which brick we compute if it is visible
    uvec3 brick = gl_GlobalInvocationID.xyz;
    if (isHelperLane(brick, g_brick_count))
        return;

    // iterate over the whole palette in this brick (read the palette size from the header)
    uint brick_id = brick_to_1D(brick, g_brick_count);
    uint brick_info_pos = brick_id * 4u;
    assert(!((g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX] < INVALID) ^^ (g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD] < g_lod_count)), "brick CUR_INV_LOD or INDEX are corrupted");


    //    // check if brick is already decoded (if anything changes, the decoder will release it)
    //    if(g_brick_info[brick_id * 4u + BRICK_INFO_CUR_INV_LOD] < g_lod_count)
    //        return;

    bool potentially_visible = false;

    uint brick_encoding_length = g_brick_starts[brick_id + 1u] - g_brick_starts[brick_id];
    EncodingRef brick_address = getBrickEncodingRef(brick_id);
    // read total palette size from brick header
#ifdef SEPARATE_DETAIL
    uint palette_size = brick_address.buf[2u * g_lod_count - 1u];
#else
    uint palette_size = brick_address.buf[2u * g_lod_count];
#endif
    assert(palette_size > 0u, "palette size 0 should not be possible");
    // check all entries in the palette if anything is visible (> 0)
    for (uint i = 1; i <= palette_size; i++) {
        if (isLabelVisible(brick_address.buf[brick_encoding_length - i])) {
            potentially_visible = true;
            break;
        }
    }

    // we can set a maximum LoD to decode to in the gui
    if(g_max_decoding_lod == 0u) {
        g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] = g_lod_count;
    }
    else if(g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] < g_lod_count) {
        g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] = min(g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD], g_max_decoding_lod);
    }

#ifndef NDEBUG
    // the coarsest LoD 0 must not be requested! we can just read it from the first palette entry during rendering so
    // we don't do anything here.
    // ToDo: we could assign the label from the palette to the brick here directly to not be required to read g_encoding in the renderer
    if(g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] == 0u) {
        assert(false, "requesting LoD 0 is not allowed!");
        g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] = g_lod_count;
    }
#endif

#ifdef SEPARATE_DETAIL
    // if the detail for this brick is not available and it is currently not decoded, we can only decode it with the base levels
    // in this case, we request the detail level of the brick to be decoded
    if(g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] == (g_lod_count - 1u)  // we request the finest LoD
    && g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD] != (g_lod_count - 1u)  // we are not already decoded up to the finest LoD
    && (g_detail_buffer_dirty == 1u || (g_detail_starts[brick_id + 1u] - g_detail_starts[brick_id]) == 0u)) {       // but the detail is not available

        g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] = g_lod_count - 2u;
        if(g_detail_requests[g_request_buffer_capacity] < g_request_buffer_capacity) {
            uint pos = atomicAdd(g_detail_requests[g_request_buffer_capacity], 1u);
            g_detail_requests[pos % g_request_buffer_capacity] = brick_id;
        }
    }
#endif

    // we deallocate if we hold a cache element.
    // only chance to not deallocate is that the brick is potentially_visible, flagged as visible in the last render
    // frame, AND decoded to the LoD requested by the renderer (this is the last else block below).
    bool deallocate = g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX] != INVALID;
    bool allocate = false;
    // no visible palette entries: brick is empty space
    if (!potentially_visible) {
        g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] = g_lod_count + 1u; // > lod_count is empty space
    }
    // bricks visibility status is unknown, we don't decode it yet since it isn't visible in the renderer currently
    else if(g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] >= g_lod_count) {
        g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] = g_lod_count;      // = lod_count is potentially visible

    }
    // brick is already flagged as visible (REQ_INV_LOD < g_lod_count) but not decoded to the requested LoD
    else if(g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD] != g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD]){
        allocate = true;
    }
    // brick is visible and already decoded to its requested level. it should remain in cache.
    else {
        assert(g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD] < g_lod_count, "visible brick is not decoded");
        assert(g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX] < g_cache_capacity, "visible brick has no cache index");
        deallocate = false;
    }

    // we can refuse to deallocate elements if the cache is filled below 75%, but only if it does not have to switch LOD
//    const uint cache_top = (g_lod_count - 1u) * ASSIGN_ELEMS_PER_LOD;
//    if (!allocate && g_assign_info[cache_top] < g_cache_capacity / 4u * 3u) {
//        deallocate = false;
//    }

    // if we switch the LoD, both allocate and deallocate have to be carried out
    if (deallocate) {
        assert(g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX] < INVALID, "trying to deallocate an INVALID brick");
        bool push_successful = pushFreeBlockStack(g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD], g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX]);
        assert(push_successful, "freeStack is full preventing correct deallocate");
        g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX] = INVALID;
        g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD] = INVALID;
    }

    assert(g_brick_info[brick_info_pos + BRICK_INFO_REQ_SLOT] == INVALID, "brick req. slot was not set to invalid before new frame");
    if (allocate) {
        // get us a unique slot index within our requested LoD
        uint lod = g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD];
        assertf(0u < lod && lod < g_lod_count, "lod=%u is not 0 < lod < lod_count while trying to allocate cache slot", lod);
        g_brick_info[brick_info_pos + BRICK_INFO_REQ_SLOT] = atomicAdd(g_assign_info[(lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_REQUESTED_BLOCKS], 1u);
    }
    else {
        assert(g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] >= g_lod_count || g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] == g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD], "we don't try to allocate even though we would need to!");
        g_brick_info[brick_info_pos + BRICK_INFO_REQ_SLOT] = INVALID;
    }

    // after this shader execution:
    // cache element ownership
    // - (BRICK_INFO_INDEX < INVALID) <=> (BRICK_INFO_CUR_INV_LOD < g_lod_count) <=> the brick still owns a cache element
    // - REQ_SLOT < INVALID <=> the brick needs a cache element <=> the REQ_SLOT is a valid entry for its REQ_LOD
    // - REQ_SLOT < INVALID => BRICK_INFO_INDEX == INVALID
    // - the ASSIGN_REQUESTED_BLOCKS for each LoD contains the number of requested blocks for this LoD.
    // - all SLOT indices < ASSIGN_REQUESTED_BLOCKS are uniquely assigned to one block each
    // visibility
    // - BRICK_INFO_REQ_INV_LOD < g_lod_count means the brick is visible in renderer AND had visible palette entries in the frame before
    // - BRICK_INFO_REQ_INV_LOD = g_lod_count means the brick contains visible labels in its palette
    // - (BRICK_INFO_REQ_INV_LOD > g_loc_count) means that the brick is guaranteed to be invisible
    // stacks
    // - if a brick is no longer visible but held an element in cache, it was freed and added to the free_block_stack
    // - the lod_counter elements at the end of the free_block_stack contain the number of requested elements per LoD
}
