#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable

layout (local_size_x = 8, local_size_y = 8) in;

#include "csgv_bindings.glsl"

// includes
#include "cpp_glsl_include/csgv_constants.h"
#include "util.glsl"
#include "debug_colormaps.glsl"
#include "morton.glsl"
#include "random.glsl"
// Compressed Segmentation Volume specific: define array containing the encoding (input) as well as the decoding (output)
#define CSGV_ENCODING_ARRAY g_encoding
#define CSGV_DETAIL_ARRAY g_detail
#define CSGV_DECODING_ARRAY g_cache
#define CSGV_READ_ONLY
#include "volcanite/compression/compressed_segmentation_volume.glsl"
#include "volcanite/compression/csgv_utils.glsl"

struct Ray {
    vec3 origin;
    vec3 direction;
};

struct AABB {
    vec3 top;
    vec3 bottom;
};


// Slab method for ray-box intersection
// @see https://martinopilia.com/posts/2018/09/17/volume-raycasting.html
// @see http://www.siggraph.org/education/materials/HyperGraph/raytrace/rtinter3.htm
void ray_box_intersection(const Ray ray, const AABB box, out float t_0, out float t_1)
{
    vec3 direction_inv = 1.0 / ray.direction;
    vec3 t_top = direction_inv * (box.top - ray.origin);
    vec3 t_bottom = direction_inv * (box.bottom - ray.origin);
    vec3 t_min = min(t_top, t_bottom);
    vec2 t = max(t_min.xx, t_min.yz);
    t_0 = max(0.0, max(t.x, t.y));
    vec3 t_max = max(t_top, t_bottom);
    t = min(t_max.xx, t_max.yz);
    t_1 = min(t.x, t.y);
}

ivec2 pixelFromInvocationID() {
    // We send out one ray per block of [g_subsampling]*[g_subsampling] pixels
    if(g_subsampling <= 1)
        return ivec2(gl_GlobalInvocationID.xy);
    else {
        // offset the subsampling pixel with some blue noise
        int blueNoiseIdx = g_blue_noise ? int(blueNoise32x32(ivec2(gl_GlobalInvocationID.xy)) * float(g_subsampling * g_subsampling)) : 0;
        return ivec2(gl_GlobalInvocationID.xy * g_subsampling) + ivec2(mod(g_subsampling_pixel + morton2Di2p(blueNoiseIdx), ivec2(g_subsampling)));
    }
}

uint get_inv_lod(ivec3 voxel) {
    // ToDo: the LOD computation is very expensive. should at least move it to the provision shader or replace it with something cheaper.
    // outside volume
    // if (any(lessThan(voxel, ivec3(0))) || any(greaterThanEqual(voxel, ivec3(g_vol_dim))))
    //    return INVALID;

    float dist = length((g_model_to_world_space * vec4((vec3(0.5f) + vec3(voxel / int(g_brick_size))) * g_brick_size, 1.f)).xyz - g_camera_position_world_space) + (float(g_brick_size)/g_world_to_model_space_scaling);
    float voxels_per_pixel_at_hit = g_voxels_per_pixel_per_dist * dist;
    return g_lod_count - 1u - clamp(uint(g_lod_bias + log2(voxels_per_pixel_at_hit)), 0u, g_lod_count - 1u);
}

/// returns true if the block is already decompressed, false otherwise
bool get_volume_label(ivec3 voxel, out uint label) {
    assert(all(greaterThanEqual(voxel.xyz, ivec3(0))) && all(lessThan(voxel.xyz, ivec3(g_vol_dim))), "trying to read volume label out of bounds!");

    if (any(lessThan(voxel, ivec3(0))) || any(greaterThanEqual(voxel, ivec3(g_vol_dim)))) {
        label = 0u;
        return true;
    }

    uvec3 brick = uvec3(voxel) / g_brick_size;
    uvec3 brick_voxel = uvec3(voxel) - (brick * g_brick_size);
    uint brick_id = brick_to_1D(brick, g_brick_count);
    uint brick_info_pos = brick_id * 4u;

    // compute optimal LOD for the center of this brick
    uint req_inv_lod = get_inv_lod(voxel);

    // tell the other shaders that we can see this brick if it's visibility state is "unknown"
    assert(g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] <= g_lod_count, "we try to access a brick that's flagged as invisible");
    if(req_inv_lod > 0 && g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] > req_inv_lod) {
        // if the brick was not requested so far:
        if(g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] >= g_lod_count)
            g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] = req_inv_lod;
        // if we request a finer level than the one that was requested so far:
        // (this should not happen if we instead compute the LOD in the provision shader)
        // ToDo: Compute a requested brick LOD in the provision shader based on the distance brick center <-> camera
        else if(req_inv_lod > g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD])
            atomicMax(g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD], req_inv_lod);
    }

    // find the current LOD
    uint cur_inv_lod = g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD];
    assert(cur_inv_lod != 0u, "BRICK_INFO_CUR_INV_LOD should never be zero");

    // special case for coarsest LOD: we can do the lookup at the first palette element for LOD_Max
    // or if the brick is not yet decoded
    if (req_inv_lod == 0u || cur_inv_lod >= g_lod_count) {
        // we could alternatively perform a small linear serach for the first *visible* label here
        label = g_encoding[g_brick_starts[brick_id+1] - 1u];
        // return false if the brick is not yet decoded but should be
        return req_inv_lod == 0u;
    }
    // read the voxel from the brick in the cache (with the currently decoded LOD)
    else {
        label = readCSGVBrick(brick_voxel, cur_inv_lod, g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX] * 8u);
        return true;
    }
}


bool isEmptySpace(ivec3 voxel) {
    uvec3 brick = uvec3(voxel / g_brick_size);
    uint brick_info_pos = brick_to_1D(brick, g_brick_count) * 4u;

    // if the brick contains nothing visible, it is empty space
    return g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] > g_lod_count;  // marked "invisible" by request shader
}



void writePixel(ivec2 pixel, vec4 color, float depth) {
    // if subsamplign is enabled, we only render one pixel per [g_subsampling]^2 block
    ivec2 subpixel;
    for(subpixel.y = 0; subpixel.y < g_subsampling; subpixel.y++) {
        for (subpixel.x = 0; subpixel.x < g_subsampling; subpixel.x++) {
            ivec2 opix = (pixel/g_subsampling)*g_subsampling + subpixel;
            if (g_camera_still_frames == 0u) {
                // writing other pixel: initialize with 0
                if (any(notEqual(opix, pixel)))
                    imageStore(feedbackOut, opix, vec4(0.f));
                // writing our pixel: invalid samples (depth < 0) will be overwritten in another frame (set .a=0)
                else
                    imageStore(feedbackOut, opix, vec4(color.rgb, depth < 0.f ? 0.f : 1.f));
            }
            else {
                vec4 prev_color = imageLoad(feedbackIn, opix);
                // writing other pixel: just copy from previous to current frame
                if (any(notEqual(opix, pixel)))
                    imageStore(feedbackOut, opix, prev_color);
                // writing our pixel, but invalid new sample (from not yet decoded brick)
                else if (depth < 0.f)
                    imageStore(feedbackOut, opix, prev_color.a > 0.f ? prev_color : vec4(color.rgb, 0.f));
                // writing our pixel with valid new sample: use previous pixel only if it already had valid samples
                else
                    imageStore(feedbackOut, opix, vec4(color.rgb, 1.f) + (prev_color.a > 0.f ? prev_color : vec4(0.f)));
            }
        }
    }
}

// all ray marching happens in the same loop to minimize thread divergence
struct RayMarchState {
    float rng;          // random number generator state
    //DDA traversal parameter
    vec3 side_dist;     // distance to the next cell in each dimension
    vec3 normal;
    ivec3 stp;
    vec3 delta;

    // ray marching
    int step;           // how many ray marching steps where done so far
    // ToDo: pos and voxel are dependend on t should we waste registers here?
    float t;            // ray distance
    vec3 pos;           // the position of the ray marcher
    ivec3 voxel;        // the current voxel in which pos is
    uint label;         // the label at the hit point
    float out_depth;    // depth to be written to the depth buffer. negative depth indicates an invalid hit

    // path tracing
    vec4 out_color;     // (radiance) color to be written to the color buffer
    vec3 throughput;   // accumulated throughput (albedo/pi * 2pi * geometry term * brdf)
    int path_length;    // number of path segments (= bounces), initialized with 0 for the view ray
};


void dda_step(inout RayMarchState state, const Ray ray) {
//    float next_t = min(state.side_dist.x, min(state.side_dist.y, state.side_dist.z));
    vec3 mask = vec3(lessThanEqual(state.side_dist.xyz, min(state.side_dist.yzx, state.side_dist.zxy)));
    state.t = dot(mask, state.side_dist);// + state.t_0;
    state.side_dist += state.delta * mask;
    state.voxel += state.stp * ivec3(mask);
    state.pos = vec4(ray.origin + state.t * ray.direction, 1.f).xyz;
    state.normal = -mask * state.stp;
}

void dda_init(inout RayMarchState state, const Ray ray) {
    // DDA traversal initialisation
    // delta.i equals to the length the ray has to travel to hit the next cell in i direction.
    // side_dist is the distance from the ray origin to the next cell in each dimension.
    vec3 rdinv = 1.0 / ray.direction;
    state.stp = ivec3( ray.direction.x >= 0.0 ? 1.0 : -1.0, ray.direction.y >= 0.0 ? 1.0 : -1.0, ray.direction.z >= 0.0 ? 1.0 : -1.0);
    state.delta = abs(rdinv); // min(rdinv * state.stp, 1.0);//
    state.side_dist = abs((vec3(state.voxel) + max(state.stp, vec3(0.0)) - ray.origin) * state.delta);
}

// ToDo: Use GGX?
float cook_torrance(const RayMarchState state, const vec3 dir_in, const vec3 dir_out) {
    // based on https://www.shadertoy.com/view/XsXXDB
    // ToDo: we have to be careful with licenses! Shadertoy code is owned by the shader authors if not stated otherwise
    const float roughness = 0.6f;
    const float F0 = 0.8f;
    //
    vec3 h = normalize(dir_in + dir_out);
    float NdotL = clamp(dot(state.normal, dir_out), 0., 1.);
    float NdotH = clamp(dot(state.normal, h), 0., 1.);
    float NdotV = clamp(dot(state.normal, dir_in), 0., 1.);
    float VdotH = clamp(dot(h, dir_in), 0., 1.);
    float rsq = roughness * roughness;

    // Geometric Attenuation
    float NH2   = 2. * NdotH / VdotH;
    float geo_b = (NH2 * NdotV);
    float geo_c = (NH2 * NdotL);
    float geo   = min(1., min(geo_b, geo_c));

    // Roughness
    // Beckmann distribution function
    float r1 = 1. / (4. * rsq * pow(NdotH, 4.));
    float r2 = (NdotH * NdotH - 1.) / (rsq * NdotH * NdotH);
    float rough = r1 * exp(r2);

    // Fresnel
    float fres = pow(1.0 - VdotH, 5.);
    fres *= (1.0 - F0);
    fres += F0;

    float spec = (NdotV * NdotL==0.) ? 0. : (fres * geo * rough) / (NdotV * NdotL);

    return spec;
}

vec3 brdf(const in RayMarchState state, const in vec3 dir_in, const in vec3 dir_out) {
    if(g_local_shading_enable) {
        // mix between Lambert and Cook Torrance specular
        const float specular = cook_torrance(state, dir_in, dir_out);
        const float diffuse = 1.f;
        return vec3((1.f - g_ratio_spec_diff) * specular + g_ratio_spec_diff * INV_PI);
    }
    else {
        // constant Lambert
        return vec3(INV_PI);
    }
}

void main() {
    // obtain pixel and fragment coordinates
    ivec2 viewport_size = imageSize(feedbackOut);

    // optional subsampling
    ivec2 pixel = pixelFromInvocationID();
    if(isHelperLane(pixel, viewport_size))
        return;

    // draw rectangles for each level-of-detail: if the volume fits into one of these rectangles it means that the
    // corresponding LoD will be selected (depends on how many voxels of the finest LoD fit into one pixel)
    if(g_debug_lod) {
        for (uint lod = 0; lod < g_lod_count; lod++) {
            if (any(greaterThanEqual(abs(ivec2(pixel) - ivec2(imageSize(feedbackOut).xy)/2), ivec2(g_vol_dim.x / (2u << lod) - 2u)))) {
                if (all(lessThanEqual(abs(ivec2(pixel) - ivec2(imageSize(feedbackOut).xy)/2), ivec2(g_vol_dim.x / (2u << lod) + 2u)))) {
                    writePixel(pixel, vec4(colormap_viridis(float(g_lod_count - 1u - lod)/float(g_lod_count - 1u)), 1.f), BACKGROUND_DEPTH);
                    return;
                }
            }
        }
    }

    // Add a subpixel offset in [0, 1) to perform temporal anti-aliasing
    vec2 subpixel_offset = randomVec3(vec2(pixel), 1347.f + float(g_camera_still_frames / (g_subsampling * g_subsampling))).xy;
    vec2 fragCoord = (vec2(pixel) + subpixel_offset) / vec2(viewport_size);

    // create view ray in model space
    Ray ray = Ray(g_camera_position_world_space, normalize((g_pixel_to_ray_direction_world_space * vec3(pixel + subpixel_offset, 1.0f)).xyz));
    ray.origin = (g_world_to_model_space * vec4(ray.origin, 1.f)).xyz;
    ray.direction = normalize(g_world_to_model_space_dir * ray.direction);
    // In world space, we hit a small cuboid (largest dimension is 1) centered around the origin.
    // We transform this to model space, where each voxel has unit size:
    float t_0, t_1;
    AABB bounding_box = AABB((g_world_to_model_space * vec4((g_bboxMin.xyz - vec3(0.5f)) * g_normalized_volume_size, 1.f)).xyz,
                             (g_world_to_model_space * vec4((g_bboxMax.xyz - vec3(0.5f)) * g_normalized_volume_size, 1.f)).xyz);
    ray_box_intersection(ray, bounding_box, t_0, t_1);
    // if we don't hit the data set, we can directly output the background
    if (t_0 >= t_1) {
        writePixel(pixel, get_background_color(fragCoord), BACKGROUND_DEPTH);
        return;
    }
    t_0 -= 0.0001f; // Epsilon

    // For debug views: only color every other pixel in the debug view to get some kind of "transparent" overlay effect
    // As we move this pixel around, the progressive accumulation averages this with the rendered colors.
    bool debug_view_visible = (pixel.x + pixel.y) % 3u != (g_frame % 3u); // < (viewport_size.x + viewport_size.y) / 2u);

    // visualize model space coordinates
    if(g_debug_model_space) {
        vec3 pos = ray.origin + t_0 * ray.direction;
        vec3 color = floor(pos) / g_physical_vol_dim;
        vec3 borders = vec3(greaterThan(fract(pos), vec3(0.0f))) * vec3(lessThan(fract(pos - vec3(0.0001f)), vec3(0.2f)));
        if(borders.x + borders.y + borders.z > 0.f)
            color *= 1.f - 1.f / (t_0 / g_world_to_model_space_scaling * 64.f);
        writePixel(pixel, vec4(color, 1.f), t_0);
        return;
    }

    // the Ray Marching State contains all information required for ray marching
    RayMarchState state;
    // ToDo: use a CPU randomly generated number instead of g_camera_still_frames to initialize the RNG?
    state.rng = float(g_frame << 16);
    state.step = 0;
    state.t = t_0;
    state.pos = ray.origin + state.t * ray.direction;
    //state.voxel = ivec3(floor(state.pos))
    state.label = INVALID;
    state.path_length = 0;
    state.throughput = vec3(1.f);
    state.out_color = vec4(0.f);
    state.out_depth = BACKGROUND_DEPTH;

    // ray marching loop
    const int MAX_PATH_LENGTH = 4;
    state.voxel = ivec3(floor(state.pos)); // DDA traversal start voxel
    dda_init(state, ray);
    for(; state.step < g_maxSteps; state.step++) {
        dda_step(state, ray);

//        if(&& any(lessThan(state.voxel, ivec3(vec3(g_vol_dim) * g_bboxMin.xyz))) || any(greaterThanEqual(state.voxel, ivec3(vec3(g_vol_dim) * g_bboxMax.xyz)))) {
//            state.ray_type = RT_NO_HIT;
//            break;
//        }

        // out of bounds and empty space check
        // ToDo: better empty space skipping - skip the non-visible brick in ONE big dda step
        if(isEmptySpace(state.voxel)
            || any(lessThan(state.voxel, ivec3(vec3(g_vol_dim) * g_bboxMin.xyz)))
            || any(greaterThanEqual(state.voxel, ivec3(vec3(g_vol_dim) * g_bboxMax.xyz)))) {
            continue;
        }

        // sampling (read value at pos from previously decoded volume segments in brick cache) or return the coarsest
        // LOD as a placeholder if not yet decoded, in which case the function will return false.
        if (!get_volume_label(state.voxel, state.label)) {
            // return an invalid depth to indicate that this sample should not be counted (= overwritten in next frame)
            state.out_color = isLabelVisible(state.label) ? get_color(state.label) : vec4(0.f);
            state.out_depth = INVALID_DEPTH;
            break;
        }

#ifndef NDEBUG
        if(state.label == INVALID){
            state.out_color = vec4(1.f, 0.f, 1.f, 1.f);
            state.out_depth = 0.f;
            assert(!isCenterWorkItem(), "get_volume_label returned INVALID. Possible corrupt data in brick cache.");
            break;
        }
#endif

        // continue traversal if this is not a valid hit
        if (!isLabelVisible(state.label)) {
            continue;
        }
        else if(debug_view_visible && g_debug_brick_cache) {
            // trigger visibility update
            uint tmp_label;
            get_volume_label(state.voxel, tmp_label);
            uvec3 brick = uvec3(state.pos.xyz * vec3(g_vol_dim)) / g_brick_size;
            uint brick_id = brick_to_1D(brick, g_brick_count);
            uint cache_start = g_brick_info[brick_id * 4u + BRICK_INFO_CACHE_INDEX];
            if (cache_start == INVALID || g_brick_info[brick_id * 4u + BRICK_INFO_CUR_INV_LOD] >= g_lod_count) {
                state.out_color = vec4(1.f, 0.f, 0.f, 1.f);
                continue;
            } else {
                state.out_color = vec4(0.f, 1.f, 0.2f, 1.f);
                break;
            }
        }
        else if (g_debug_normals) {
            state.out_color = vec4((state.normal + vec3(1.f)) * vec3(0.5f), 1.f);
            state.throughput = vec3(0.f);
            break;
        }


        // VIEW_RAY TO SURFACE HIT
        {
//            // visualize visible brick id
//            uvec3 brick = uvec3(state.voxel) / g_brick_size;
//            uint brick_id = brick.x + brick.y * g_brick_count.x + brick.z * (g_brick_count.x * g_brick_count.y);
//            state.out_color = vec4(integer2colorlabel(brick_id, false), 1.f);
//            break;

            // classification determines the surface color (= suface albedo)
            vec4 surface_albedo_opacity = get_color(state.label);
            // debug: visualize level-of-detail with viridis colormap
            if (g_debug_lod) { // && debug_view_visible
                uint lod = get_inv_lod(state.voxel);
                if(lod != INVALID) {
                    surface_albedo_opacity.rgb = (state.out_color.rgb + 3.f * colormap_viridis(float(lod)/float(g_lod_count - 1u))) / 4.f;
                }
            }

            // the first surface hit is the only point for which we want to store our t value in the depth buffer
            if(state.path_length == 0)
                state.out_depth = state.t;
            // opacity is always 1 on hit
            state.out_color.a = 1.f;

            // include ambient lighting factor - not physically based
            state.out_color.rgb += state.throughput * surface_albedo_opacity.rgb * g_factor_ambient;
            state.throughput *= 1.f - g_factor_ambient;

            // emission
//            state.out_color.rgb += state.throughput * surface_albedo_opacity.rgb;

            // early ray termination
            if(max(state.throughput.x, max(state.throughput.y, state.throughput.z)) < 0.05f) {
                state.throughput = vec3(0.f);
                break;
            }

            // store previous direction as the outgoing direction for the BRDF evaluation
            vec3 prev_direction = -ray.direction;

            // sample a new direction
            // g_shadow_ao_ray_distr controls the ratio between rays sampled in any direction and rays in light direction
            // this allows user control between direct and indirect illumination
            if(nextRNG(fragCoord, state.rng).x < g_shadow_ao_ray_distr) {
                if(g_local_shading_enable) {
                    // sample the cosine weighted positive hemisphere
                    ray.direction = sampleCosineWeightedHemisphere(nextRNG(fragCoord, state.rng).xy, state.normal);
                    state.throughput /= pdfCosineWeightedHemisphere(ray.direction, state.normal);
                } else {
                    ray.direction = uniformSampleHemisphereVoxel(nextRNG(fragCoord, state.rng).xy, state.normal);
                    state.throughput *= TWO_PI;
                }
            }
            else {
                // sample directly to  directional light
                // ToDo: get the probabilities right so that this is real next event estimation?
                ray.direction = g_light_direction;
                // ToDo: is it right to treat this as the PDF of uniform hemisphere sampling? Feels right at least..
                state.throughput *= TWO_PI;

                // check for self shadowing of the current voxel
                if (g_shadow_ray_enable > 0 && dot(state.normal, ray.direction) < 0) {
                    // same code as for a shadow hit!
                    state.throughput = vec3(0.f);
                    break;
                }
                // force an early ray termination
                state.path_length = MAX_PATH_LENGTH - 1;
            }
            ray.direction = normalize(ray.direction);

#ifndef NDEBUG
            assert(dot(state.normal, ray.direction) >= 0.f, "sampling a new ray direction from the *negative* hemisphere");
            if(dot(state.normal, ray.direction) < 0.f) {
                state.out_color.rgb = vec3(1.f, 0.f, 1.f);
                break;
            }
#endif

            // surface albedo and Monte Carlo factor 2*PI
            state.throughput *= surface_albedo_opacity.rgb;
            if(g_local_shading_enable) {
                // geometry term
                state.throughput *= max(dot(state.normal, ray.direction), 0.f);
                // brdf
                state.throughput *= brdf(state, ray.direction, prev_direction);
            } else {
                state.throughput /= TWO_PI;
            }

            // if we do not trace any secondary rays, we can stop the traversal here
            if(g_shadow_ray_enable == 0) {
                break;
            }

            // re-init DDA traversal for the shadow ray
            ray.origin = state.pos;
            dda_init(state, ray);
            state.path_length++;
        }

        // RAY TERMINATION
        if(state.path_length > MAX_PATH_LENGTH) {
            break;
        }
        // Russian Roulette (ToDo: only when this is not a ray to the light source / NEE!)
//        float roulette_probability = max(state.throughput.r, max(state.throughput.g, state.throughput.b));
//        if (nextRNG(fragCoord, state.rng).x > roulette_probability) {
//            break;
//        }
//        state.throughput /= roulette_probability;
    }

    if(g_debug_step_count) {
        atomicAdd(gpu_raymarch_samples, state.step);
        atomicAdd(gpu_bbox_hits, 1u);
    }

    state.out_color.rgb += state.throughput * vec3(g_light_intensity);

    // ToDo: the background should be added in the csgv_upsample_resolve shader
    // perform alpha blending with background
    state.out_color.rgb = get_background_color(fragCoord).rgb * (1.f - state.out_color.a) + state.out_color.rgb * state.out_color.a;

    // write to iamge
    writePixel(pixel, state.out_color, state.out_depth);
}
