#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_buffer_reference_uvec2 : require

layout (local_size_x = 8, local_size_y = 8) in;

#include "csgv_bindings.glsl"

// includes
#include "cpp_glsl_include/csgv_constants.h"
#include "util.glsl"
#include "debug_colormaps.glsl"
#include "morton.glsl"
#include "random.glsl"
#include "dummy_envmap.glsl"
// Compressed Segmentation Volume specific: define array containing the encoding (input) as well as the decoding (output)
#define CSGV_ENCODING_ARRAY g_encoding
#define CSGV_DETAIL_ARRAY g_detail
#define CSGV_DECODING_ARRAY g_cache
#define CSGV_READ_ONLY
#include "volcanite/compression/compressed_segmentation_volume.glsl"
#include "volcanite/compression/csgv_utils.glsl"

struct Ray {
    vec3 origin;
    vec3 direction;
};

struct AABB {
    vec3 top;
    vec3 bottom;
};


// Slab method for ray-box intersection
// @see https://martinopilia.com/posts/2018/09/17/volume-raycasting.html
// @see http://www.siggraph.org/education/materials/HyperGraph/raytrace/rtinter3.htm
void ray_box_intersection(const Ray ray, const AABB box, out float t_0, out float t_1)
{
    vec3 direction_inv = 1.0 / ray.direction;
    vec3 t_top = direction_inv * (box.top - ray.origin);
    vec3 t_bottom = direction_inv * (box.bottom - ray.origin);
    vec3 t_min = min(t_top, t_bottom);
    vec2 t = max(t_min.xx, t_min.yz);
    t_0 = max(0.0, max(t.x, t.y));
    vec3 t_max = max(t_top, t_bottom);
    t = min(t_max.xx, t_max.yz);
    t_1 = min(t.x, t.y);
}

ivec2 pixelFromInvocationID() {
    // We send out one ray per block of [g_subsampling]*[g_subsampling] pixels
    if(g_subsampling <= 1)
        return ivec2(gl_GlobalInvocationID.xy);
    else {
        // offset the subsampling pixel with some blue noise
        int blueNoiseIdx = g_blue_noise_enable ? int(blueNoise32x32(ivec2(gl_GlobalInvocationID.xy)) * float(g_subsampling * g_subsampling)) : 0;
        return ivec2(gl_GlobalInvocationID.xy * g_subsampling) + ivec2(mod(g_subsampling_pixel + morton2Di2p(blueNoiseIdx), ivec2(g_subsampling)));
    }
}

uint get_inv_lod(ivec3 voxel) {
    // Ensure the same level-of-detail for all bricks by computing it from the brick's center.
    // Otherwise, different levels-of-detail would be requested for decompression of the same brick.
    vec3 brick_center_world_space = (g_model_to_world_space * vec4((vec3(0.5f) + vec3(voxel / int(g_brick_size))) * g_brick_size, 1.f)).xyz;
    float dist = length(brick_center_world_space - g_camera_position_world_space) + (float(g_brick_size)/g_world_to_model_space_scaling);

    // use the MSB as a fast log2 (rounding down to int anyways)
    int voxels_per_pixel_at_hit = int(g_voxels_per_pixel_per_dist * dist);
    // clamp with a potential user specified max inverse. LoD
    return min(g_lod_count - 1u - uint(clamp(g_lod_bias + findMSB(voxels_per_pixel_at_hit), 0, g_lod_count - 1u)), g_max_inv_lod);
}

bool isDepthValid(float depth) { return depth >= 0.f; }

/// returns a label for this voxel but sets valid to invalid if it was read from a brick that was not decoded up to the requested level
uint get_volume_label(ivec3 voxel, inout float depth_valid) {
    assert(all(greaterThanEqual(voxel.xyz, ivec3(0))) && all(lessThan(voxel.xyz, ivec3(g_vol_dim))), "trying to read volume label for out of bounds voxel!");

    uvec3 brick = uvec3(voxel) / g_brick_size;
    uvec3 brick_voxel = uvec3(voxel) - (brick * g_brick_size);
    uint brick_idx = brick_pos2idx(brick, g_brick_count);
    uint brick_info_pos = brick_idx * 4u;

    // compute optimal LOD for the center of this brick
    uint req_inv_lod = get_inv_lod(voxel);

    // tell the other shaders that we can see this brick if it's visibility state is "unknown"
    // but only if this is a valid pixel sample. An invalid sample could be accessing bricks that are actually not visible.
    assert(g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] <= g_lod_count, "we try to access a brick that's flagged as invisible");
    if(isDepthValid(depth_valid) && req_inv_lod > 0 && g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] > req_inv_lod) {
        // if the brick was not requested so far:
        if(g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] >= g_lod_count)
            g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] = req_inv_lod;
        // if we request a finer level than the one that was requested so far:
        // (this should not happen if we instead compute the LOD in the provision shader)
        // ToDo: Compute a requested brick LOD in the provision shader based on the distance brick center <-> camera
        else if(req_inv_lod > g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD])
            atomicMax(g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD], req_inv_lod);
    }

    // find the current LOD
    uint cur_inv_lod = g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD];
    assert(cur_inv_lod != 0u, "BRICK_INFO_CUR_INV_LOD should never be zero");

    // special case for coarsest LOD: we can do the lookup at the first palette element for LOD_Max
    // or if the brick is not yet decoded
    if (req_inv_lod == 0u || cur_inv_lod >= g_lod_count) {

        EncodingRef encoding_address = getBrickEncodingRef(brick_idx);
        uint encoding_size = getBrickEncodingLength(brick_idx);

        // if the brick was not decoded, sample a random palette entry
        if(req_inv_lod > 0u && g_max_inv_lod > 0u) {
            uint palette_size = getBrickPaletteLength(brick_idx);

            // indicate the smaple as invalid (if it is not a homogeneous brick)
            if(palette_size > 1u)
                depth_valid = INVALID_DEPTH;
            // ToDo: this should be a random number from the random state
            float rnd = hash(uvec3(gl_GlobalInvocationID.xy, g_frame)).r;
            return  encoding_address.buf[encoding_size - 1u - uint(rnd * rnd * float(palette_size))];
        }

        // return the first palette entry = coarsests compressed representation of the brick for inv_lod 0
        // we could alternatively perform a small linear search for the first *visible* label here
        return  encoding_address.buf[encoding_size - 1u];
    }
    // read the voxel from the brick in the cache (with the currently decoded LOD)
    else {
        // ToDo: we do not change the depth_valid validity here even though we do NOT check if we request an LOD that differs from what is currently decoded for the brick
#ifdef PALETTE_CACHE
        return readCSGVPaletteBrick(brick_voxel, cur_inv_lod, g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX], brick_idx);
#else
        return readCSGVBrick(brick_voxel, cur_inv_lod, g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX]);
#endif
    }
}


bool isEmptySpace(ivec3 voxel) {
    assertf(all(greaterThanEqual(voxel, ivec3(0))) && all(lessThan(voxel, g_vol_dim)), "empty space request for invalid voxel %v3i", voxel);

    uvec3 brick = uvec3(voxel / g_brick_size);
    uint brick_info_pos = brick_pos2idx(brick, g_brick_count) * 4u;

    // if the brick contains nothing visible, it is empty space
    return g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] > g_lod_count;  // marked "invisible" by request shader
}


void writePixel(ivec2 pixel, vec4 color, float depth_valid) {

    // invalidate any nan samples
    if (any(isnan(color)) || any(isinf(color)) || isnan(depth_valid) || isinf(depth_valid)) {
        color = vec4(1.f, 0.f, 1.f, 1.f);
        depth_valid = -abs(depth_valid);
    }

    // if subsamplign is enabled, we only render one pixel per [g_subsampling]^2 block
    ivec2 subpixel;
    for (subpixel.y = 0; subpixel.y < g_subsampling; subpixel.y++) {
        for (subpixel.x = 0; subpixel.x < g_subsampling; subpixel.x++) {
            ivec2 opix = (pixel/g_subsampling)*g_subsampling + subpixel;
            if (g_camera_still_frames == 0u) {
                // writing other pixel: initialize with 0
                if (any(notEqual(opix, pixel)))
                    imageStore(feedbackOut, opix, vec4(0.f));
                // writing our pixel: invalid samples (depth < 0) will be overwritten in another frame (set .a < 0)
                else
                    imageStore(feedbackOut, opix, vec4(color.rgb, isDepthValid(depth_valid) ? 1.f :  -1.f));
            }
            else {
                vec4 prev_color = imageLoad(feedbackIn, opix);
                // writing other pixel: just copy from previous to current frame
                if (any(notEqual(opix, pixel)))
                    imageStore(feedbackOut, opix, prev_color);
                // writing our pixel, but invalid new sample (from not yet decoded brick)
                else if (!isDepthValid(depth_valid))
                    imageStore(feedbackOut, opix, prev_color.a > 0.f ? prev_color : vec4(color.rgb, -1.f));
                // writing our pixel with valid new sample: use previous pixel only if it already had valid samples
                else
                    imageStore(feedbackOut, opix, vec4(color.rgb, 1.f) + (prev_color.a > 0.f ? prev_color : vec4(0.f)));
            }
        }
    }
}

// all ray marching happens in the same loop to minimize thread divergence
struct RayMarchState {
    float rng;          ///< random number generator state
    int step;           ///< how many ray marching steps where done so far

    // DDA traversal parameter
    ivec3 step_sign;    ///< voxel step direction per axis, either -1 or 1
    vec3 inv_ray_dir;   ///< t distance required for one unit voxel step along each axis
    // the DDA position is split into integer voxel and sub-voxel position to avoid numerical floating point problems
    ivec3 voxel;        ///< current voxel of the DDA ray marching position
    vec3 pos_in_voxel;  ///< sub-voxel position of the DDA position in [0,1)^3

    // shading and G-Buffer
    float depth_valid;  ///< depth to be written to the depth buffer. negative depth indicates an invalid sample
    vec3 normal;        ///< normal at the current position
    uint label;         ///< label at the current position
    uint last_label;    ///< label of the previous position

    // path tracing
    vec4 out_color;     ///< (radiance) color to be written to the color buffer
    vec3 throughput;    ///< accumulated throughput (albedo/pi * 2pi * geometry term * brdf [+ volumetric attenuation])
    int path_length;    ///< number of path segments (= bounces), initialized with 0 for the view ray
};

#define SHADOW_RAY_PATH_LENGTH -1

// checks some state variables and ray origin / direction for inf or nan values. returns false if any are found.
bool checkStateAndRay(const RayMarchState state, const Ray ray, int line) {
    if (any(isnan(state.voxel + state.pos_in_voxel)) || any(isinf(state.voxel + state.pos_in_voxel))
        || (any(isnan(state.pos_in_voxel)) || any(isinf(state.pos_in_voxel)))
        || (any(isnan(ray.origin)) || any(isinf(ray.origin)))
        ||  (any(isnan(ray.direction)) || any(isinf(ray.direction)))) {
            debugPrintfEXT("nan/inf in line %i, step %i   state.pos: %v3f | sub_voxel_pos: %v3f | state.t: %f | state.inv_ray_dir: %v3f | ray %v3f -> %v3f",
                            line, state.step, state.voxel + state.pos_in_voxel, state.pos_in_voxel,
                            length((state.voxel + state.pos_in_voxel) - ray.origin),
                            state.inv_ray_dir, ray.origin, ray.direction);
        return false;
    }
    return true;
}


void dda_step_multilevel(inout RayMarchState state, const Ray ray, int voxel_size) {
    // Round down to do the traversal in one pseudo-voxel with a size of [voxel_size] many fine-resolution voxels
    // To avoid handling negative voxels, assume normal voxel size 1 in that case. Altneratively, we would have to use
    // floating point and floor the coarse position. e.g. integer div. maps (-1, 0, 0) with voxel_size 2 to (0, 0, 0)
    assert(voxel_size == 1 || !any(lessThan(state.voxel, ivec3(0))), "multi-level DDA voxel size must be 1 for voxel positions < 0");

    ivec3 big_voxel = state.voxel / voxel_size;
    vec3 pos_in_big_voxel = (vec3(state.voxel % voxel_size) + state.pos_in_voxel) / float(voxel_size);

    // determine distances that t has to change until the ray hits the next voxel edge
    // note: if a ray direction axis is 0, inv_ray_dir is INFTY and step_sign is 1 to yield INFTY which is > all others
    // note: side_dist_t is always positive as inv_ray_dir is negative if and only if step_sign is negative
    vec3 side_dist_t = state.inv_ray_dir * ( max(state.step_sign, vec3(0.f)) - pos_in_big_voxel );

    assertf(all(greaterThanEqual(side_dist_t, vec3(0.f))) || !any(isnan(side_dist_t)), "next_t nan/negative: %v3f", side_dist_t);

    // get axis along which to step as mask[argmin(next_t)] = 1
    // note: lessThanEqual(min(side_dist.yzx)..) computations can produce masks with multiple 1 entries.
    int axis = 0;
    if (side_dist_t.z < side_dist_t.x && side_dist_t.z < side_dist_t.y)
        axis = 2;
    else if (side_dist_t.y < side_dist_t.x && side_dist_t.y < side_dist_t.z)
        axis = 1;

    assertf(ray.direction[axis] != 0.f && !isinf(side_dist_t[axis]), "step along invalid axis. side_dist_t: %v3f", side_dist_t);

    // advance voxel along the selcted axis
    big_voxel[axis] += state.step_sign[axis];

    // update sub-voxel position
    pos_in_big_voxel = fract(pos_in_big_voxel + (side_dist_t[axis] * ray.direction));
    const float ONE_MINUS_EPSILON = 0.9999999f;
    pos_in_big_voxel[axis] = max(-state.step_sign[axis], 0.f) * ONE_MINUS_EPSILON;

    state.voxel = big_voxel * voxel_size + ivec3(floor(pos_in_big_voxel * voxel_size));
    state.pos_in_voxel = fract(pos_in_big_voxel * voxel_size);

    // update normal
    state.normal = vec3(0.f);
    state.normal[axis] = float(-state.step_sign[axis]);
}

void dda_step(inout RayMarchState state, const Ray ray) {
    checkStateAndRay(state, ray, __LINE__);

    // determine distances that t has to change until the ray hits the next voxel edge
    // note: if a ray direction axis is 0, inv_ray_dir is INFTY and step_sign is 1 to yield INFTY which is > all others
    // note: side_dist_t is always positive as inv_ray_dir is negative if and only if step_sign is negative
    vec3 side_dist_t = state.inv_ray_dir * ( max(state.step_sign, vec3(0.f)) - state.pos_in_voxel );

    assertf(all(greaterThanEqual(side_dist_t, vec3(0.f))) || !any(isnan(side_dist_t)), "next_t nan/negative: %v3f", side_dist_t);

    // get axis along which to step as mask[argmin(next_t)] = 1
    // note: lessThanEqual(min(side_dist.yzx)..) computations can produce masks with multiple 1 entries.
    int axis = 0;
    if (side_dist_t.z < side_dist_t.x && side_dist_t.z < side_dist_t.y)
        axis = 2;
    else if (side_dist_t.y < side_dist_t.x && side_dist_t.y < side_dist_t.z)
        axis = 1;

    assertf(ray.direction[axis] != 0.f && !isinf(side_dist_t[axis]), "step along invalid axis. side_dist_t: %v3f", side_dist_t);

    // advance voxel along the selcted axis
    state.voxel[axis] += state.step_sign[axis];

    // update sub-voxel position
    state.pos_in_voxel = fract(state.pos_in_voxel + (side_dist_t[axis] * ray.direction));
    const float ONE_MINUS_EPSILON = 0.9999999f;
    state.pos_in_voxel[axis] = max(-state.step_sign[axis], 0.f) * ONE_MINUS_EPSILON;

    // update normal
    state.normal = vec3(0.f);
    state.normal[axis] = float(-state.step_sign[axis]);

    if (!checkStateAndRay(state, ray, __LINE__)) {
        debugPrintfEXT(" step %i ray origin %v3f dir %v3f: axis %i", state.step, ray.origin, ray.direction, axis);
    }
}

void dda_init(inout RayMarchState state, const Ray ray, float t_0) {
    vec3 init_raypos = ray.origin + t_0 * ray.direction;
    state.voxel = ivec3(floor(init_raypos));
    state.pos_in_voxel = init_raypos - state.voxel;

    state.step_sign = ivec3(ray.direction.x >= 0.f ? 1 : -1,
                            ray.direction.y >= 0.0 ? 1 : -1,
                            ray.direction.z >= 0.0 ? 1 : -1);

    // ray.direction may be zero somewhere. set inv_ray_dir and step_sign so that dda_step will yield positive infinity
    // for side_dist_t in the respective axis. This way, the traversal will never step into that direction.
    state.inv_ray_dir = 1.f / ray.direction;
    const float INFINITY = 1.f / 0.f;
    if(ray.direction.x == 0.f) {
        state.inv_ray_dir.x = INFINITY;
        state.step_sign.x = 1;
    }
    if(ray.direction.y == 0.f) {
        state.inv_ray_dir.y = INFINITY;
        state.step_sign.y = 1;
    }
    if(ray.direction.z == 0.f) {
        state.inv_ray_dir.z = INFINITY;
        state.step_sign.z = 1;
    }

    checkStateAndRay(state, ray, __LINE__);
}

// ToDo: Use GGX?
float cook_torrance(const in RayMarchState state, const in vec3 dir_in, const in vec3 dir_out) {
    // based on https://www.shadertoy.com/view/XsXXDB
    // ToDo: we have to be careful with licenses! Shadertoy code is owned by the shader authors if not stated otherwise
    const float roughness = 0.4f;
    const float F0 = 0.8f;
    //
    vec3 h = normalize(dir_in + dir_out);
    float NdotL = clamp(dot(state.normal, dir_out), 0.f, 1.f);
    float NdotH = clamp(dot(state.normal, h), 0.f, 1.f);
    float NdotV = clamp(dot(state.normal, dir_in), 0., 1.f);
    float VdotH = clamp(dot(h, dir_in), 0.f, 1.f);
    float rsq = roughness * roughness;

    // Geometric Attenuation
    float NH2   = 2.f * NdotH / VdotH;
    float geo_b = (NH2 * NdotV);
    float geo_c = (NH2 * NdotL);
    float geo   = min(1.f, min(geo_b, geo_c));

    // Roughness
    // Beckmann distribution function
    float r1 = 1.f / (4.f * rsq * pow(NdotH, 4.f));
    float r2 = (NdotH * NdotH - 1.f) / (rsq * NdotH * NdotH);
    float rough = r1 * exp(r2);

    // Fresnel
    float fres = pow(1.f - VdotH, 5.f);
    fres *= (1.f - F0);
    fres += F0;

    float spec = (NdotV * NdotL <= 0.f) ? 0.f : (fres * geo * rough) / (NdotV * NdotL);

    return spec;
}

vec3 brdf(const in RayMarchState state, const in vec3 dir_in, const in vec3 dir_out) {
    if(g_local_shading_enable) {
        // mix between Lambert and Cook Torrance specular
        const float specular = cook_torrance(state, dir_in, dir_out);
        const float diffuse = 1.f;
        return vec3((1.f - g_ratio_spec_diff) * specular + g_ratio_spec_diff * INV_PI);
    }
    else {
        // constant Lambert
        return vec3(INV_PI);
    }
}

void main() {
    // obtain pixel and fragment coordinates
    ivec2 viewport_size = imageSize(feedbackOut);

    // optional subsampling
    ivec2 pixel = pixelFromInvocationID();
    if(isHelperLane(pixel, viewport_size))
        return;

    // draw rectangles for each level-of-detail: if the volume fits into one of these rectangles it means that the
    // corresponding LoD will be selected (depends on how many voxels of the finest LoD fit into one pixel)
    if(g_debug_lod) {
        for (uint lod = 0; lod < g_lod_count; lod++) {
            if (any(greaterThanEqual(abs(ivec2(pixel) - ivec2(imageSize(feedbackOut).xy)/2), ivec2(g_vol_dim.x / (2u << lod) - 2u)))) {
                if (all(lessThanEqual(abs(ivec2(pixel) - ivec2(imageSize(feedbackOut).xy)/2), ivec2(g_vol_dim.x / (2u << lod) + 2u)))) {
                    writePixel(pixel, vec4(colormap_viridis(float(g_lod_count - 1u - lod)/float(g_lod_count - 1u)), 1.f), BACKGROUND_DEPTH);
                    return;
                }
            }
        }
    }

    // Add a subpixel offset in [0, 1) to perform temporal anti-aliasing
    vec2 subpixel_offset = hash(uvec3(pixel.x, pixel.y, 1347 + g_camera_still_frames / (g_subsampling * g_subsampling))).xy;
    vec2 fragCoord = (vec2(pixel) + subpixel_offset) / vec2(viewport_size);

    // create view ray in model space
    Ray ray = Ray(g_camera_position_world_space, normalize((g_pixel_to_ray_direction_world_space * vec3(pixel + subpixel_offset, 1.0f)).xyz));
    ray.origin = (g_world_to_model_space * vec4(ray.origin, 1.f)).xyz;
    ray.direction = normalize(g_world_to_model_space_dir * ray.direction);
    // In world space, we hit a small cuboid (largest dimension is 1) centered around the origin.
    // We transform this to model space, where each voxel has unit size:
    // ToDo: voxels having unit size in model space does not work with the voxel_size parameter, no?
    float t_0, t_1;
    AABB bounding_box = AABB((g_world_to_model_space * vec4((g_bboxMin.xyz - vec3(0.5f)) * g_normalized_volume_size, 1.f)).xyz,
                             (g_world_to_model_space * vec4((g_bboxMax.xyz - vec3(0.5f)) * g_normalized_volume_size, 1.f)).xyz);
    ray_box_intersection(ray, bounding_box, t_0, t_1);
    // if we don't hit the data set, we can directly output the background
    if (t_0 >= t_1) {
        if(g_debug_envmap) {
            // ToDo: expensive inverse as the matrix may contain scaling. use scaling and transpose(rotation) instead
            ray.direction = normalize(inverse(g_world_to_model_space_dir) * ray.direction);
            writePixel(pixel, vec4(g_light_intensity * dummy_envmap(ray.direction), 1.f), BACKGROUND_DEPTH);
        }
        else
            writePixel(pixel, get_background_color(fragCoord), BACKGROUND_DEPTH);
        return;
    }

    // For debug views: only color every other pixel in the debug view to get some kind of "transparent" overlay effect
    // As we move this pixel around, the progressive accumulation averages this with the rendered colors.
    bool debug_view_visible = (pixel.x + pixel.y) % 3u != (g_frame % 3u); // < (viewport_size.x + viewport_size.y) / 2u);

    // visualize model space coordinates
    if(g_debug_model_space) {
        vec3 pos = ray.origin + t_0 * ray.direction;
        vec3 color = floor(pos) / vec3(g_vol_dim);
        vec3 borders = vec3(greaterThan(fract(pos), vec3(0.0f))) * vec3(lessThan(fract(pos - vec3(0.0001f)), vec3(0.2f)));
        if(borders.x + borders.y + borders.z > 0.f)
            color *= 1.f - 1.f / (t_0 / g_world_to_model_space_scaling * 64.f);
        writePixel(pixel, vec4(color, 1.f), t_0);
        return;
    }


    RayMarchState state;
    state.rng = float(g_camera_still_frames << 16);
    state.label = INVALID;
    state.last_label = INVALID;
    state.path_length = 0;
    state.throughput = vec3(1.f);
    state.out_color = vec4(0.f);
    state.depth_valid = BACKGROUND_DEPTH;
    // initialize DDA traversal with t_0  offset to prevent aliasing
    dda_init(state, ray, t_0 - 0.01f);

    // ray marching loop
    for(state.step = 0; state.step < g_maxSteps; state.step++) {

        // single-level DDA traversal step
//         dda_step(state, ray);
        // multi-level DDA traversal step
        {
            // determine size of the coarse traversal voxel in 2^n number of fine-resolution voxels
            uint dda_voxel_size;

            // edge cases not handled in multi-level DDA:
            //  - internal integer division does not handle negative voxel coordinates
            //  - upper volume borders may lie in the middle of a coarse voxel
            if (any(lessThan(state.voxel, ivec3(vec3(g_vol_dim) * g_bboxMin.xyz)))
                || any(greaterThanEqual(state.voxel, ivec3(vec3(g_vol_dim) * g_bboxMax.xyz))))
                dda_voxel_size = 1u;
            // empty space skipping: move into next brick
            else if (isEmptySpace(state.voxel))
                dda_voxel_size = g_brick_size;
            // normal traversal:
            else
                dda_voxel_size = g_brick_size >> get_inv_lod(state.voxel);

            dda_step_multilevel(state, ray, int(dda_voxel_size));
        }

#ifndef NDEBUG
        if(!checkStateAndRay(state, ray, __LINE__)) {
            state.out_color = vec4(1.f, 0.f, 0.f, 1.f);
            state.depth_valid = 0.f;
            break;
        }
#endif

        // out of bounds check
        if(any(lessThan(state.voxel, ivec3(vec3(g_vol_dim) * g_bboxMin.xyz)))
            || any(greaterThanEqual(state.voxel, ivec3(vec3(g_vol_dim) * g_bboxMax.xyz)))) {
            // we may have started out of bounds
            if(state.path_length > 0 || state.step > 16)
                break;
            else
               continue;
        }

        // empty space check
        if(isEmptySpace(state.voxel)) {
//#define VISUALIZE_EMPTY_SPACE
#ifndef VISUALIZE_EMPTY_SPACE
            continue;
#else
            const float empty_space_opacity = 0.005f;
            state.out_color.rgb += state.throughput * vec3(state.throughput.r, 0.f, 1.f - state.throughput.r) * empty_space_opacity;
            state.throughput *= 1.f - empty_space_opacity;
            state.out_color.a = max(state.out_color.a, 1.f - (state.throughput.r + state.throughput.g + state.throughput.b) / 3.f);
            continue;
        } else {
            const float empty_space_opacity = 0.005f;
            state.out_color.rgb += state.throughput * vec3(1.f - state.throughput.r, state.throughput.r, 0.f) * empty_space_opacity;
            state.throughput *= 1.f - empty_space_opacity;
            state.out_color.a = max(state.out_color.a, 1.f - (state.throughput.r + state.throughput.g + state.throughput.b) / 3.f);
#endif
        }


        // sampling (read value at pos from previously decoded volume segments in brick cache) or return a
        // placeholder label if not yet decoded, in which case the depth_valid will be set to INVALID_DEPTH.
        // An sample marked as invalid this way may not alter the framebuffer and skip certain cmoputation steps.
        state.last_label = state.label;
        state.label = get_volume_label(state.voxel, state.depth_valid);
//        if (!isValid(state.depth_valid)) {
//            // only allow stepping one brick width further
//            state.step = int(g_maxSteps - g_brick_size);
//            state.step = int(g_maxSteps);
////            state.out_color = isLabelVisible(state.label) ? get_color(state.label) : vec4(0.f);
////            state.throughput = vec3(0.f);
////            break;
//        }

#ifndef NDEBUG
        if(state.label == INVALID){
            state.out_color = vec4(1.f, 0.f, 1.f, 1.f);
            state.depth_valid = 0.f;
            assert(!isCenterWorkItem(), "get_volume_label returned INVALID. Possible corrupt data in brick cache.");
            break;
        }
#endif

        // obtain material at the current position
        int material = getMaterial(state.label);

        // continue traversal if this is not a visible label
        // material < 0 <=> !isLabelVisible(state.label)
        if (material < 0) {
            continue;
        }
        else if(debug_view_visible && g_debug_brick_cache) {
            uvec3 brick = uvec3(state.voxel) / g_brick_size;
            uvec3 brick_voxel = uvec3(state.voxel) - (brick * g_brick_size);
            uint brick_info_pos = brick_pos2idx(brick, g_brick_count) * 4u;

            uint cache_start = g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX];
            if (cache_start == INVALID || g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD] >= g_lod_count) {
                state.out_color = vec4(1.f, 0.f, 0.f, 1.f);
                continue;
            } else if (g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD] < g_lod_count) { // should always be true here
                uint lod = g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD];
                state.out_color.rgb = colormap_viridis(float(lod - 1u)/float(g_lod_count - 2u));
                if(lod == 0u)
                    state.out_color.rgb = vec3(1.f, 0.f, 0.f);
                state.out_color.a = 1.f;
                state.throughput = vec3(0.f);
            } else {
                state.out_color = (state.out_color + 3.f * vec4(0.f, 1.f, 0.2f, 1.f)) / 4.f;
                state.throughput = vec3(0.f);
                break;
            }
        }
        else if (g_debug_normals) {
            state.out_color = vec4(-min(state.normal, vec3(0.f)) * 0.5f + max(state.normal, vec3(0.f)), 1.f);
            state.throughput = vec3(0.f);
            break;
        }

        // obtain surface albedo / volume emission and opacity
        vec4 surface_albedo_opacity = getColor(state.label, material);

        // ENTER SEMI-TRANSPARENT VOLUME
        // ToDo: integrate this into the correct path tracing interaction, simplify BRDF sampling e.g. https://boksajak.github.io/files/CrashCourseBRDF.pdf
        if (surface_albedo_opacity.a < 1.f) {
            if(state.last_label != state.label) {
                // add the contribution of a semi-transparent surface (local shading only)
                if(false && g_local_shading_enable) {
                    //if(dot(state.normal, -ray.direction) > 0.f)
                    state.out_color.rgb += state.throughput * surface_albedo_opacity.rgb * surface_albedo_opacity.a * brdf(state, g_light_direction, -ray.direction) * TWO_PI * max(dot(state.normal, g_light_direction), 0.f) * g_light_intensity;
                }
                else {
                    state.out_color.rgb += state.throughput * surface_albedo_opacity.rgb * surface_albedo_opacity.a;
                }

                // throughput is reduced by the opacity of the surface
                state.throughput *= 1.f - surface_albedo_opacity.a;
                // update pixel alpha
                state.out_color.a = max(state.out_color.a, surface_albedo_opacity.a);
            }

            // emission and absorption from homogeneous volume (ignoring scattering!)
//            // find distance the ray will travel in the next step
//            float next_t = dot(vec3(lessThanEqual(state.next_t.xyz, min(state.next_t.yzx, state.next_t.zxy))), state.next_t);
//            // compute transmittance of homogeneous voluem segment
//            vec3 transmittance = exp(-surface_albedo_opacity.a * abs(next_t - state.t) * (1.f - surface_albedo_opacity.rgb));
//            // update opacity (computed over inverse opacity = transmittance)
//            state.out_color.a = max(state.out_color.a, 1.f - ((1.f - state.out_color.a) * (transmittance.r + transmittance.g + transmittance.b)/3.f));
//            // add volume emission
//            state.out_color.rgb += state.throughput * surface_albedo_opacity.rgb * (1.f - transmittance);
//            state.throughput *= transmittance;
        }
        // HIT OPAQUE SURFACE
        else {
//            // visualize visible brick id
//            uvec3 brick = uvec3(state.voxel) / g_brick_size;
//            uint brick_idx = brick_pos2idx(brick, g_brick_count);
//            state.out_color = vec4(integer2colorlabel(brick_idx, false), 1.f);
//            break;

            // break if this was a shadow ray
            if(state.path_length == SHADOW_RAY_PATH_LENGTH) {
                state.throughput = vec3(0.f);
                break;
            }

            // debug: visualize level-of-detail with viridis colormap
            if (g_debug_lod) { // && debug_view_visible
                uint lod = get_inv_lod(state.voxel);
                if(lod != INVALID) {
                    surface_albedo_opacity.rgb = (state.out_color.rgb + 3.f * colormap_viridis(float(lod)/float(g_lod_count - 1u))) / 4.f;
                }
            }

            // the first surface hit is the only point for which we want to store our t value in the depth buffer
            // but if we previously stored an INVALID_DEPTH (< 0) at any point, we don't want to overwrite that
            if(state.path_length == 0) {
                float t = length((state.voxel + state.pos_in_voxel) - ray.origin);
                state.depth_valid = min(state.depth_valid, t);
            }
            // opacity is always 1 on hit
            state.out_color.a = 1.f;

            // include ambient lighting factor - not physically based but interpolates between non-shaded and shaded
            if(state.path_length == 0) {
                state.out_color.rgb += state.throughput * surface_albedo_opacity.rgb * g_factor_ambient;
                state.throughput *= 1.f - g_factor_ambient;
            }

            // emission
            if(g_materials[material].emission > 0.f) {
                state.out_color.rgb += state.throughput * surface_albedo_opacity.rgb * g_materials[material].emission;
            }

            // early ray termination
            if(max(state.throughput.x, max(state.throughput.y, state.throughput.z)) <= 0.f) {
                state.throughput = vec3(0.f);
                break;
            }

            // store previous direction as the outgoing direction for the BRDF evaluation
            vec3 brdf_out_direction = -ray.direction;

            // advance the path: sample a new direction
            state.path_length++;
            // g_shadow_pathtracing_ratio controls the ratio between rays sampled in any direction and rays in light direction
            // this allows user control between direct and indirect illumination
            if(g_global_illumination_enable && nextRNG(fragCoord, state.rng).x < g_shadow_pathtracing_ratio) {
                if(g_local_shading_enable) {
                    // sample the cosine weighted positive hemisphere
                    ray.direction = sampleCosineWeightedHemisphereVoxel(nextRNG(fragCoord, state.rng).xy, state.normal);
                    state.throughput /= pdfCosineWeightedHemisphere(ray.direction, state.normal);
                } else {
                    ray.direction = sampleUniformHemisphereVoxel(nextRNG(fragCoord, state.rng).xy, state.normal);
                    state.throughput /= pdfUniformHemisphere(ray.direction, state.normal);
                }
            }
            else {
                // sample directly to  directional light
                ray.direction = g_light_direction;
                // ToDo: get the probabilities right so that this is real next event estimation?. Is it right to treat this as the PDF of uniform hemisphere sampling? Looks okay at least..
                state.throughput /= pdfUniformHemisphere(ray.direction, state.normal);  // 1/(2*PI)

                // check for self shadowing of the current voxel ToDo: should not happen?
                if (g_global_illumination_enable && dot(state.normal, ray.direction) < 0) {
                    state.throughput = vec3(0.f);
                    break;
                }
                // mark this ray as a shadow ray
                state.path_length = SHADOW_RAY_PATH_LENGTH;
            }

            #ifndef NDEBUG
                checkStateAndRay(state, ray, __LINE__);
            #endif

            // surface albedo
            state.throughput *= surface_albedo_opacity.rgb;
            if(g_local_shading_enable) {
                // geometry term
                state.throughput *= max(dot(state.normal, ray.direction), 0.f);
                // brdf
                state.throughput *= brdf(state, ray.direction, brdf_out_direction);
            } else {
                state.throughput /= TWO_PI;
            }

            // if we do not trace any secondary rays, we can stop the traversal here
            if(!g_global_illumination_enable) {
                break;
            }


            // Russian Roulette (only when this is not a ray to the light source / NEE)
            if(state.path_length != SHADOW_RAY_PATH_LENGTH && state.path_length < g_max_path_length) {
                float survival_probability = max(state.throughput.r, max(state.throughput.g, state.throughput.b));
                if (nextRNG(fragCoord, state.rng).x > survival_probability) {
                    state.throughput = vec3(0.f);
                    break;
                }
                state.throughput /= survival_probability;
            }

            // re-init DDA traversal for the shadow ray
            ray.origin = state.voxel + state.pos_in_voxel;
            dda_init(state, ray, 0.f);
        }

        // ray termination
        if(state.path_length > g_max_path_length) {
            state.throughput = vec3(0.f);
            break;
        }
    }
    // we did not find any light source
    if(state.step >= g_maxSteps || state.path_length == 0)
        state.throughput = vec3(0.f);

    if(g_debug_step_count) {
        atomicAdd(gpu_raymarch_samples, state.step);
        atomicAdd(gpu_bbox_hits, 1u);
    }

    if(g_envmap_enable) {
        ray.direction = normalize(inverse(g_world_to_model_space_dir) * ray.direction);
        state.out_color.rgb += state.throughput * vec3(g_light_intensity) * dummy_envmap(ray.direction);
    }
    else
        state.out_color.rgb += state.throughput * vec3(g_light_intensity);

    // ToDo: the background should be added in the csgv_upsample_resolve shader
    // perform alpha blending with backgroun
    if(g_debug_envmap)
        state.out_color.rgb = vec3(g_light_intensity) * dummy_envmap(ray.direction) * (1.f - state.out_color.a) + state.out_color.rgb * state.out_color.a;
    else
        state.out_color.rgb = get_background_color(fragCoord).rgb * (1.f - state.out_color.a) + state.out_color.rgb * state.out_color.a;


    // write to image
    writePixel(pixel, state.out_color, state.depth_valid);
}
