#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_buffer_reference_uvec2 : require

layout (local_size_x = 8, local_size_y = 4, local_size_z = 4) in;


#include "csgv_bindings.glsl"

// includes
#include "cpp_glsl_include/csgv_constants.h"
#include "util.glsl"
#include "volcanite/compression/csgv_utils.glsl"

void main() {
    uvec3 brick = gl_GlobalInvocationID.xyz;
    if(isHelperLane(brick, g_brick_count))
    return;
    uint brick_idx = brick_pos2idx(brick, g_brick_count);

    if(brick.x == 0 && brick.y == 0 && brick.z == 0) {
        // clear per-LoD info buffers (that all start at inv. LoD 1, so we need lod-count-1 workers for this)
        for(uint inv_lod_minus_one = 0u; inv_lod_minus_one < g_lod_count - 1; inv_lod_minus_one++) {
            // clear all free_block_stacks
            g_free_block_stacks[(g_lod_count - 1u) * g_free_stack_capacity + inv_lod_minus_one] = 0u;
            // clear all assign_info
            g_assign_info[inv_lod_minus_one * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_START] = INVALID;
            g_assign_info[inv_lod_minus_one * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_COUNT] = 0u;
            g_assign_info[inv_lod_minus_one * ASSIGN_ELEMS_PER_LOD + ASSIGN_REQUESTED_BLOCKS] = 0u;
        }

        // reset the cache top counter (= free all cache elements)
        g_assign_info[(g_lod_count - 1u) * ASSIGN_ELEMS_PER_LOD] = 0u;
        #ifdef SEPARATE_DETAIL
        // reset the atomic counter for the detail request buffer
        g_detail_requests[g_request_buffer_capacity] = 0u;
        #endif
    }

        #ifdef SEPARATE_DETAIL
    // clear the request buffer
    uint total_workers = g_brick_count.x * g_brick_count.y * g_brick_count.z;
    uint elems_per_worker = (g_request_buffer_capacity + total_workers - 1u) / total_workers;
    for(uint i = elems_per_worker * brick_idx; i < elems_per_worker * (brick_idx + 1); i++) {
        if(i < g_request_buffer_capacity)
        g_detail_requests[i] = INVALID;
    }
        #endif


    // reset cache info
    g_brick_info[brick_idx * 4u + BRICK_INFO_REQ_INV_LOD] = INVALID; // ToDo: for a "garbage collection" we would overwrite this to directly re-assign all required blocks
    g_brick_info[brick_idx * 4u + BRICK_INFO_CUR_INV_LOD] = INVALID;
    g_brick_info[brick_idx * 4u + BRICK_INFO_CACHE_INDEX] = INVALID;
    g_brick_info[brick_idx * 4u + BRICK_INFO_REQ_SLOT] = INVALID;
}
