#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_buffer_reference_uvec2 : require

layout (local_size_x = 4, local_size_y = 4, local_size_z = 4) in;


#include "csgv_bindings.glsl"

// includes
#include "util.glsl"
#include "volcanite/compression/csgv_utils.glsl"
#define CSGV_DECODING_ARRAY g_cache
#include "volcanite/compression/compressed_segmentation_volume.glsl"

uint popFreeBlockStack(uint inv_lod) {
    uint pos = atomicAdd(g_free_block_stacks[(g_lod_count - 1u) * g_free_stack_capacity + (inv_lod - 1u)], uint(-1)) - 1u;
    if(pos > g_free_stack_capacity) {
        // no element on stack for us
        //assert(false, "couldn't pop from block stack because it is empty - or the counter was invalid");
        atomicAdd(g_free_block_stacks[(g_lod_count - 1u) * g_free_stack_capacity + (inv_lod - 1u)], 1u);
        return INVALID;
    }
    else {
        return g_free_block_stacks[(inv_lod - 1u) * g_free_stack_capacity + pos];
    }
}

void main() {
    // at the beginning of this shader execution:
    // ASSIGN_NEW_BLOCK_START contains the first index (measured in base elements) in g_cache where the new elements for this LoD can start
    // ASSIGN_NEW_BLOCK_COUNT contains the number of elements (measured in LxLxL elements) in g_cache for this LoD available from there
    // (the other elements we will try to fetch from the freeBlockStack)
    //
    // cache element ownership
    // - (BRICK_INFO_INDEX < INVALID) <=> (BRICK_INFO_CUR_INV_LOD < g_lod_count) <=> the brick still owns a cache element
    // - REQ_SLOT < INVALID <=> the brick needs a cache element <=> the REQ_SLOT is a valid entry for its REQ_LOD
    // - REQ_SLOT < INVALID => BRICK_INFO_INDEX == INVALID
    // - the ASSIGN_REQUESTED_BLOCKS for each LoD contains the number of requested blocks for this LoD.
    // - all SLOT indices < ASSIGN_REQUESTED_BLOCKS are uniquely assigned to one block each
    // visibility
    // - BRICK_INFO_REQ_INV_LOD < g_lod_count means the brick is visible in renderer AND had visible palette entries in the frame before
    // - BRICK_INFO_REQ_INV_LOD = g_lod_count means the brick contains visible labels in its palette
    // - (BRICK_INFO_REQ_INV_LOD > g_loc_count) means that the brick is guaranteed to be invisible

    // find out for which brick we compute if it is visible
    uvec3 brick = gl_GlobalInvocationID.xyz;
    if (isHelperLane(brick, g_brick_count))
        return;

    // do some debug checks
    if(!isHelperLane(brick, uvec3(1u))) {
        const uint cache_top = (g_lod_count - 1u) * ASSIGN_ELEMS_PER_LOD;
        assertf(g_assign_info[cache_top] <= g_cache_capacity, "cache counter is over capacity!", g_assign_info[cache_top]);
    }

    uint brick_idx = brick_pos2idx(brick, g_brick_count);
    uint brick_info_pos = brick_idx * 4u;
    assert(!((g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX] < INVALID) ^^ (g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD] < g_lod_count)), "brick CUR_INV_LOD or INDEX are corrupted");


    // track how many bricks are decoded of each LOD
    if(g_debug_step_count && g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD]  > 0 && g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] < g_lod_count) {
        atomicAdd(gpu_blocks_in_cache[g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] - 1u], 1u);
    }

    uint slot = g_brick_info[brick_info_pos + BRICK_INFO_REQ_SLOT];
    // not assigned to a request slot means we can ignore this element
    if(slot == INVALID) {
        // the renderer should flag everything visible again
        g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] = max(g_lod_count, g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD]);
        return;
    }

    uint inv_lod = g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD];
    uint elemSizeInCache = 1u << (3u * (inv_lod - 1u)); // number of base elements we need for storing one element of this LoD in g_cache
    assert(0 < inv_lod && inv_lod < g_lod_count, "brick has slot index but requests zero or invalid lod");

    // now find us an index in the cache
    uint cache_idx = INVALID;
    // the first slots can directly use one of the "new" elements.
    if(slot < g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_COUNT]) {
        cache_idx = g_assign_info[(inv_lod - 1u) * ASSIGN_ELEMS_PER_LOD + ASSIGN_NEW_BLOCK_START] + slot * elemSizeInCache;
    }
    // the others have to grab one from the freeBlockStack
    else {
        cache_idx = popFreeBlockStack(inv_lod);
    }


    // see if we have a valid index in the cache
    if(cache_idx != INVALID) {
        uvec3 valid_brick_size = clamp(g_vol_dim.xyz - brick * g_brick_size, uvec3(0u), uvec3(g_brick_size));
#if 1
    #ifdef SEPARATE_DETAIL
            assert(!(inv_lod == g_lod_count - 1U && (g_detail_buffer_dirty == 1u || g_detail_starts[brick_idx] == g_detail_starts[brick_idx+1])), "detail buffers marked dirty but the provision shader requested detail decoding");
    #endif
            resetCSGVBrick(cache_idx * g_cache_base_element_uints, inv_lod);
            decompressCSGVBrick(brick_idx, getBrickEncodingLength(brick_idx), valid_brick_size, 0u, inv_lod, cache_idx * g_cache_base_element_uints);
#else
        // fill the cache with "random" indices into the brick's palette
        fillCSGVBrick(cache_idx * g_cache_base_element_uints, inv_lod, brick_idx % getBrickPaletteSize(brick_idx));
#endif
        g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD] = inv_lod;
    }
    // if not.. try again next time
    else {
        g_brick_info[brick_info_pos + BRICK_INFO_CUR_INV_LOD] = INVALID;
    }
    g_brick_info[brick_info_pos + BRICK_INFO_CACHE_INDEX] = cache_idx;
    g_brick_info[brick_info_pos + BRICK_INFO_REQ_SLOT] = INVALID;   // if we couldn't obtain an element this frame, this will be set again in the next frame

    // the renderer should flag everything visible again
    g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD] = max(g_lod_count, g_brick_info[brick_info_pos + BRICK_INFO_REQ_INV_LOD]);
}
