#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_buffer_reference_uvec2 : require

layout (local_size_x = 8, local_size_y = 8) in;

#include "csgv_bindings.glsl"
#include "util.glsl"
#include "volcanite/compression/csgv_utils.glsl"

vec3 rgb2srgb(vec3 x) {
    return pow(x, vec3(2.2f));
}

vec3 tonemap_ACES(vec3 x)
{
    float a = 2.51f;
    float b = 0.03f;
    float c = 2.43f;
    float d = 0.59f;
    float e = 0.14f;
    return clamp((x*(a*x+b))/(x*(c*x+d)+e), vec3(0.f), vec3(1.f));
}

float gaussian(float x, float sigma) {
    return exp(-0.5 * (x * x) / (sigma * sigma));
}

void main() {
    // obtain pixel and fragment coordinates
    const ivec2 viewport_size = imageSize(inpaintedOutColor);
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

    // We output a low resolution image were multiple pixel are merged into one if the image does not have all pixels set yet
    // The current_block_size is the dimension of the pixel block in which one sample is guaranteed to be rendererd already.
    // After a certain number of frames, this will constantly be 1 because each pixel got at least one sample.
    const int current_block_size = clamp(g_subsampling / (1 << int(log2(sqrt(g_camera_still_frames + 1)))), 1, g_subsampling);

    // only one thread per pixel block
    if(isHelperLane(pixel, viewport_size))
        return;


    // read the HDR radiance that was accumulated for this pixel so far
    vec4 pixel_color = imageLoad(feedbackOut, pixel);
    // the alpha channel stores the number of samples this pixel received so far
    //   - a negative value indicates invalid samples that accessed undecoded voxels.
    //   - a value of 0 indicates that the pixel did not receive any samples yet (only occurs with g_subsampling > 1).
    //   - a positive value indicates that these samples are valid and will not be overwritten until the camera moves.
    pixel_color.a = abs(pixel_color.a);

    // unpack the G-Buffer for the pixel
    float normalized_depth;
    vec3 normal;
    uint label_hash;
    uvec2 g_buffer_packed = imageLoad(gBuffer, pixel).rg;
    unpackGBufferRG8(g_buffer_packed, label_hash, normal, normalized_depth);


    // rgb stores radiance sum, alpha stores number of samples
    vec4 accum_color = pixel_color;
    // a simple bilateral filter for denoising
    if (g_denoise) {
        accum_color = vec4(0.f);
        // compute an average of all pixels in this
        ivec2 block_pixel;
        float weight = 1.f;
        float normalization  = 0.f;
        for (int i = -g_denoise_filter_kernel_size; i < g_denoise_filter_kernel_size; i++) {
            for (int j = -g_denoise_filter_kernel_size; j < g_denoise_filter_kernel_size; j++) {
                block_pixel.x = pixel.x + i;
                block_pixel.y = pixel.y + j;

                if(any(lessThan(block_pixel, ivec2(0))) || any(greaterThanEqual(block_pixel, viewport_size)))
                    continue;

                // weight the pixel colors by sample counts
                vec4 rgb_samples = imageLoad(feedbackOut, block_pixel);
                // we take the abs because invalid samples are marked with a sample count < 0 (usually -1)
                if(abs(rgb_samples.a) > 0.f) {
                    float normalized_depth_temp;
                    vec3 normal_temp;
                    uint label_hash_temp;
                    uvec2 g_buffer_packed_temp = imageLoad(gBuffer, block_pixel).rg;
                    if (!unpackGBufferRG8(g_buffer_packed_temp, label_hash_temp, normal_temp, normalized_depth_temp)) continue;

                    if (normal.x != normal_temp.x || normal.y != normal_temp.y || normal.z != normal_temp.z) continue;
                    if (abs(float(normalized_depth) - float(normalized_depth_temp)) + 0.001f > g_difference_depth_denoising) continue;

                    float spatial_gaussian = 1.f;
                    if (g_spatial_sigma > 0)
                        spatial_gaussian = gaussian(length(vec2(i, j)), g_spatial_sigma);

                    float depth_gaussian = 1.f;
                    if (g_depth_sigma > 0)
                        depth_gaussian.r = gaussian((pixel_color.r + pixel_color.g + pixel_color.b) - (rgb_samples.r + rgb_samples.g + rgb_samples.b), g_depth_sigma);
//                        depth_gaussian.r = gaussian(length(pixel_color.rgb - rgb_samples.rgb), g_depth_sigma);

                    float weight = spatial_gaussian * depth_gaussian;

                    accum_color.rgb += (rgb_samples.rgb) * weight;
                    accum_color.a += abs(rgb_samples.a) * weight;
                    normalization  += weight;
                }
            }
        }

        if (normalization  > 0.f)
            accum_color.rgba /= normalization ;

        if (pixel.x + pixel.y < (viewport_size.x + viewport_size.y) / 2)
            accum_color = pixel_color;

        if (accum_color.rgb == vec3(0)) accum_color = pixel_color;
    }

    // weight by sample count
    if(accum_color.a > 0.f)
        accum_color.rgb /= accum_color.a;

    // perform tonemapping and color space conversion
    if(g_tonemap_enable) {
        accum_color.rgb *= 2.4f; // increase exposure
        accum_color.rgb = tonemap_ACES(accum_color.rgb);
        accum_color.rgb = rgb2srgb(accum_color.rgb);
    }

    // output to display image
    imageStore(inpaintedOutColor, pixel, vec4(accum_color.rgb, 1.f));
}
