//  Copyright (C) 2024, Max Piochowiak, Karlsruhe Institute of Technology
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.

#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_buffer_reference_uvec2 : require

#define INFINITY 1.f/0.f

layout (local_size_x = 8, local_size_y = 8) in;

layout (set = 0, binding = 0, rgba8) uniform restrict writeonly image2D outColor;

#include "util.glsl"
#include "transfer_function.glsl"
#include "blending.glsl"
#include "random.glsl"

layout (std140, set = 0, binding = 1) uniform render_info {
    mat4 g_model_to_world_space;
    mat4 g_world_to_model_space;
    mat3 g_world_to_model_space_dir;
    mat4 g_world_to_projection_space;
    mat4 g_projection_to_world_space;
    mat4 g_projection_to_view_space;
    mat4 g_view_to_world_space;
    mat4 g_world_to_view_space;
    mat4 g_view_to_projection_space;
    mat3 g_pixel_to_ray_direction_world_space;
    vec3 g_camera_position_world_space;
    vec4 g_background_color_a;
    vec4 g_background_color_b;
    float g_transferFunction_limits_min;
    float g_transferFunction_limits_max;
    float g_stepSize;
    int g_maxSteps;
    float g_opacityThreshold;
    bool g_debug_model_space;
};

struct Ray {
    vec3 origin;
    vec3 direction;
};

struct AABB {
    vec3 top;
    vec3 bottom;
};


// Slab method for ray-box intersection
// @see https://martinopilia.com/posts/2018/09/17/volume-raycasting.html
// @see http://www.siggraph.org/education/materials/HyperGraph/raytrace/rtinter3.htm
void ray_box_intersection(const Ray ray, const AABB box, out float t_0, out float t_1)
{
    vec3 direction_inv = 1.0 / ray.direction;
    vec3 t_top = direction_inv * (box.top - ray.origin);
    vec3 t_bottom = direction_inv * (box.bottom - ray.origin);
    vec3 t_min = min(t_top, t_bottom);
    vec2 t = max(t_min.xx, t_min.yz);
    t_0 = max(0.0, max(t.x, t.y));
    vec3 t_max = max(t_top, t_bottom);
    t = min(t_max.xx, t_max.yz);
    t_1 = min(t.x, t.y);
}





void main() {
    // obtain pixel and fragment coordinates
    ivec2 viewport_size = imageSize(outColor);
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    if (isHelperLane(pixel, viewport_size)) {
        return;
    }
    vec2 fragCoord = (vec2(pixel) + vec2(0.5)) / vec2(viewport_size);
    vec2 ndc = fragCoord * 2.f - vec2(1.f);

    // create view ray (in world space)
    Ray world_ray = Ray(g_camera_position_world_space, normalize(g_pixel_to_ray_direction_world_space * vec3(pixel, 1.0f)));

    // model space for the volume is always the unit cube [0,0,0] to [1,1,1] which simplifies texture access
    // but in world space, this AABB may be scaled or translated
    float t_0, t_1;
    AABB bounding_box = AABB((g_model_to_world_space * vec4(0.f, 0.f, 0.f, 1.f)).xyz,
                             (g_model_to_world_space * vec4(1.f, 1.f, 1.f, 1.f)).xyz);
    ray_box_intersection(world_ray, bounding_box, t_0, t_1);
    // we don't hit the data set -> background
    if (t_0 >= t_1) {
        float bgWeight = (fragCoord.x*2.f + (1.f-fragCoord.y)) / 3.f;
        bgWeight *= bgWeight;
        vec4 bgColor = g_background_color_a * (1.f - bgWeight) + g_background_color_b * bgWeight;
        bgColor.rgb *= bgColor.a;
        imageStore(outColor, pixel, bgColor);
        return;
    }

    vec4 pos = g_world_to_model_space * vec4(world_ray.origin + t_0 * world_ray.direction, 1.f);


    // visualize model space coordinates
    if(g_debug_model_space) {
        imageStore(outColor, pixel, vec4(pos.xyz, 1.f));
        return;
    }

    // TODO implement raymarching etc.

    imageStore(outColor, pixel, vec4(0.f));
    return;
}
