#version 460
#extension GL_GOOGLE_include_directive : enable

layout (local_size_x = 8, local_size_y = 8) in;

layout (set = 0, binding = 0, rgba8) uniform restrict writeonly image2D IMAGE_out;
layout (set = 0, binding = 1) uniform sampler2D SAMPLER_in;

void main() {

    ivec2 viewport_size = imageSize(IMAGE_out);
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    vec2 fragCoord = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5)) / vec2(viewport_size);

    float in_val = texture(SAMPLER_in, fragCoord).r;
    vec4 result_col = vec4(vec3(0.5f), in_val * 0.5f);
    imageStore(IMAGE_out, pixel, result_col);
}
