#version 460
#extension GL_GOOGLE_include_directive : enable

layout (local_size_x = 8, local_size_y = 8) in;

layout(std430, set = 0, binding = 0) buffer sequence_buffer
{
    int g_rle[];
};
layout(std430, set = 0, binding = 1) buffer index_buffer
{
    uvec2 g_indices[]; //  start position in rle_buffer and length of seqeunce
};

layout (std140, row_major, set = 0, binding = 2) uniform compression_options {
    int brick_size;
    int frame;
};

#include "util.glsl"
#include "volcanite/compression/compression_utils.glsl"

void main() {

}
