#version 460
#extension GL_GOOGLE_include_directive : enable

layout (local_size_x = 8, local_size_y = 8) in;

layout(std430, set = 0, binding = 0) buffer sequence_buffer
{
    int g_rle[];
};

layout(std430, set = 0, binding = 1) buffer index_buffer
{
    ivec2 g_indices[]; //  start position in rle_buffer and additional info
};

layout (std140, row_major, set = 0, binding = 2) uniform compression_options {
    int brick_size;
    ivec3 brick_dim;
    int frame;
    int sequence_offset;
    int order_variants;
};

layout(std430, set = 0, binding = 3) readonly buffer sequence_order
{
    ivec4 g_order[]; // maps sequence index to voxel position within brick
};

layout (set = 0, binding = 4, r16ui) uniform readonly uimage3D IMAGE_volume;

#include "util.glsl"
#include "volcanite/compression/compression_utils.glsl"

void main() {
    ivec3 brick_idx = ivec3(gl_GlobalInvocationID.xyz);
    int brick_idx_1D_no_frame = brick_to_1D(brick_idx, brick_dim, 0);
    if (isHelperLane(brick_idx, brick_dim)) {
        return;
    }
    ivec3 volume_size = imageSize(IMAGE_volume);
    ivec3 voxel_start = brick_idx * brick_size;
    int brick_voxel_count = brick_size * brick_size * brick_size;

    // TODO: we only do this for one frame (because only one frame fits into the sequence buffer).
    // next Step: squeeze the downlaoded sequence buffer on the CPU, get the length of that, and upload it as sequence_offset
    // the index_buffer is global with the final value, but the sequence buffer should be offset by this value

    ivec3 pos;
    int rle_count, v, v_entry;

    // [1] FIND ORDER WITH MIN RLE ENCODING LENGTH ---------------------------------------------------------------------
    int min_order_variant = 0;
    int min_order_variant_length = brick_voxel_count * 2;
    for(int order_variant=0; order_variant<order_variants; order_variant++) { //TODO: not <6 but < order_variants instead
        rle_count = 1; // we use this variable to count HOW MANY entries we have instead of the length of single entries
        v = int(imageLoad(IMAGE_volume, voxel_start + g_order[order_variant * brick_voxel_count].xyz).r);
        v_entry = v;
        for (int i = 1; i < brick_voxel_count; i++) {
            // only access valid positions. keep old value otherwise (these entries vanish in the compression)
            pos = voxel_start + g_order[order_variant * brick_voxel_count + i].xyz;

            if (all(greaterThanEqual(pos, ivec3(0))) && all(lessThan(pos, volume_size))) {
                v = int(imageLoad(IMAGE_volume, pos).r);
            }
            // count every new entry
            if (v != v_entry) {
                rle_count++;
                v_entry = v;
            }
        }
        // check if we found a new minimal order
        if(rle_count < min_order_variant_length) {
            min_order_variant_length = rle_count;
            min_order_variant = order_variant;
        }
    }

    // [2] RLE COMPRESSION BY APPLYING MIN ORDER -----------------------------------------------------------------------
    int sequence_start = 2 * brick_voxel_count * brick_idx_1D_no_frame; // each brick get's 2*it's size as rle entries (worst case)
    int sequence_i = sequence_start; // iterator through the sequence buffer

    rle_count = 1;// an rle entry is at least 1 long
    v = int(imageLoad(IMAGE_volume, voxel_start + g_order[min_order_variant * brick_voxel_count].xyz).r);
    v_entry = v;
    int last_v = v;
    for (int i = 1; i < brick_voxel_count; i++) {
        // only access valid positions. keep old value otherwise (these entries vanish in the compression)
        pos = voxel_start + g_order[min_order_variant * brick_voxel_count + i].xyz;

        if (all(greaterThanEqual(pos, ivec3(0))) && all(lessThan(pos, volume_size))) {
            v = int(imageLoad(IMAGE_volume, pos).r) - last_v;
        }

        // same entry
        if (v == v_entry) {
            rle_count++;
        }
        // finished entry
        else {
            g_rle[sequence_i++] = rle_count;// this many times..
            g_rle[sequence_i++] = v_entry;// ..this value occurred

            // start new entry
            rle_count = 1;
            v_entry = v;
        }
    }
    // write the final entry
    g_rle[sequence_i++] = rle_count;  // this many times..
    g_rle[sequence_i++] = v_entry;    // ..this value occurred

    // update the index buffer
    // we only store the LENGTH so far. on the CPU this is converted to the correct start location in the sequence buffer
    int brick_idx_1D = brick_to_1D(brick_idx, brick_dim, frame);
    g_indices[brick_idx_1D].x = sequence_i - sequence_start;
    g_indices[brick_idx_1D].y = min_order_variant; // additional info about the brick compression
}
