#version 460
#extension GL_GOOGLE_include_directive : enable

layout (local_size_x = 8, local_size_y = 8) in;

layout(std430, set = 0, binding = 0) readonly buffer sequence_buffer
{
    int g_rle[];
};

layout(std430, set = 0, binding = 1) readonly buffer index_buffer
{
    ivec2 g_indices[]; //  start position in rle_buffer and additional info
};

layout (std140, row_major, set = 0, binding = 2) uniform compression_options {
    int brick_size;
    ivec3 brick_dim;
    int frame;
    int sequence_offset;
    int order_variants;
};

layout(std430, set = 0, binding = 3) readonly buffer sequence_order
{
    ivec4 g_order[]; // maps sequence index to voxel position within brick
};

layout (set = 0, binding = 4, r16ui) uniform readonly uimage3D IMAGE_volume;

layout(std430, set = 1, binding = 5) buffer verify_output
{
    ivec4 verify_errors;
};

#include "util.glsl"
#include "volcanite/compression/compression_utils.glsl"

void main() {
    ivec3 brick_idx = ivec3(gl_GlobalInvocationID.xyz);
    if (isHelperLane(brick_idx, brick_dim)) {
        return;
    }

    ivec3 volume_size = imageSize(IMAGE_volume);
    int sequence_i = g_indices[brick_pos2idx(brick_idx, brick_dim, frame)].x;
    int order_variant = g_indices[brick_pos2idx(brick_idx, brick_dim, frame)].y;
    ivec3 voxel_start = brick_idx * brick_size;

    uint val;
    int count;

    // iterate through rle buffer
    int voxel_max = brick_size * brick_size * brick_size;
    int v = 0;
    while(v < voxel_max) {

        // read next entry from rle sequence buffer
        count = g_rle[sequence_i++];
        val = uint(g_rle[sequence_i++]);

        if(count < 1) {
            atomicAdd(verify_errors.y, 1);
            return;
        }
        if(sequence_i > (frame+1) * brick_dim.x * brick_dim.y * brick_dim.z * voxel_max * 2) {
            atomicAdd(verify_errors.z, 1);
            return;
        }

        for(int j = 0; j < count; j++) {

            if (v >= voxel_max) {
                atomicAdd(verify_errors.w, 1);
                break;
            }

            ivec3 voxel = voxel_start + g_order[order_variant * voxel_max + v].xyz;

            if (all(lessThan(voxel, volume_size))) {
                // imageStore(IMAGE_volume, voxel, ivec4(val));
                if (val != imageLoad(IMAGE_volume, voxel).r)
                    atomicAdd(verify_errors.x, 1);
            }

            v++;
        }
    }


//
//
//    int brick_idx_1D_no_frame = brick_pos2idx(brick_idx, brick_dim, 0);
//    if (isHelperLane(brick_idx, brick_dim)) {
//        return;
//    }
//    ivec3 volume_size = imageSize(IMAGE_volume);
//    ivec3 voxel_start = brick_idx * brick_size;
//    int brick_voxel_count = brick_size * brick_size * brick_size;
//    int sequence_start = 2 * brick_voxel_count * brick_idx_1D_no_frame; // each brick get's 2*it's size as rle entries (worst case)
//    int sequence_i = sequence_start; // iterator through the sequence buffer
//
//    // TODO: we only do this for one frame (because only one frame fits into the sequence buffer).
//    // next Step: squeeze the downlaoded sequence buffer on the CPU, get the length of that, and upload it as sequence_offset
//    // the index_buffer is global with the final value, but the sequence buffer should be offset by this value
//
//    ivec3 pos;
//    int rle_count = 1; // an rle entry is at least 1 long
//    int v = int(imageLoad(IMAGE_volume, voxel_start + g_order[0].xyz).r);
//    int v_entry = v;
//    for(int i = 1; i < brick_voxel_count; i++) {
//        // only access valid positions. keep old value otherwise (these entries vanish in the compression)
//        pos = voxel_start + g_order[i].xyz;
//        if(all(greaterThanEqual(pos, ivec3(0))) && all(lessThan(pos, volume_size))) {
//            v = int(imageLoad(IMAGE_volume, pos).r);
//        }
//
//        // same entry
//        if(v == v_entry) {
//            rle_count++;
//        }
//        // finished entry
//        else {
//            g_rle[sequence_i++] = rle_count; // this many times..
//            g_rle[sequence_i++] = v_entry;    // ..this value occurred
//
//            // start new entry
//            rle_count = 1;
//            v_entry = v;
//        }
//    }
//
//    // write the final entry
//    g_rle[sequence_i++] = rle_count;  // this many times..
//    g_rle[sequence_i++] = v_entry;    // ..this value occurred
//
//    // update the index buffer
//    // we only store the LENGTH so far. on the CPU this is converted to the correct start location in the sequence buffer
//    int brick_idx_1D = brick_pos2idx(brick_idx, brick_dim, frame);
//    g_indices[brick_idx_1D].x = sequence_i - sequence_start;
//    g_indices[brick_idx_1D].y = 0; // we can store additional info here.
}
