#version 460
#extension GL_GOOGLE_include_directive : enable

layout (local_size_x = 8, local_size_y = 8) in;

layout (set = 0, binding = 0, r16ui) uniform readonly uimage3D IMAGE_volume;
layout (set = 0, binding = 1, r16ui) uniform restrict writeonly uimage3D IMAGE_out;

#include "util.glsl"

void main() {
    ivec3 outSize = imageSize(IMAGE_out);
    ivec3 idx = ivec3(gl_GlobalInvocationID.xyz);

    if (isHelperLane(idx, outSize)) {
        return;
    }

    uint value = imageLoad(IMAGE_volume, idx).r;
    imageStore(IMAGE_out, idx, uvec4(value));
}
